### ISSUE TITLE
Can't create layer "expanded_conv_add/add" of type "AddV2"

### ISSUE THREAD

**Issue by dbacea** [opencv/opencv#16399]
**System information (version)**
OpenCV => 4.2.0
Operating System / Platform => Windows 10 64 bit
Compiler => Visual Studio 2019
TensorFlow 2.1.0

**Detailed description**
I have trained a MobileNetV2 using tf.keras. Then I exported the model as frozen graph *.pb file, and tried to load the network using cv::dnn::readNetFromTensorflow(). When I run the app the following error occurs:
`OpenCV(4.2.0) Error: Unspecified error (Can't create layer "expanded_conv_add/add" of type "AddV2") in cv::dnn::dnn4_v20191202::LayerData::getLayerInstance, file C:\build\master_winpack-build-win64-vc14\opencv\modules\dnn\src\dnn.cpp, line 562
`

When using TensorFlow version 1.14 for creating the model and then save the frozen graph, this kind of error does not appear

**Steps to reproduce**
The .pb file is found inside the attached .zip file

`_net = cv::dnn::readNetFromTensorflow(pathToPbFile);`

[MobileNetV2Alpha0.10.zip](https://github.com/opencv/opencv/files/4091426/MobileNetV2Alpha0.10.zip)

**Comment by dkurt** [comment]
Fixed by https://github.com/opencv/opencv/pull/16263 (10 days after 4.2.0 release). Please try master branch instead.

**Comment by dbacea** [comment]
any idea @alalek  @dkurt when will be the next release?

**Comment by dkurt** [comment]
@dbacea, you may enable this model with current release as well.

For it, you need to have a `.pbtxt` file which is nothing but a text copy of `.pb` without weights:

```python
import tensorflow as tf

with tf.gfile.FastGFile('MobileNetV2Alpha0.10.pb', "rb") as f:
    graph_def = tf.GraphDef()
    graph_def.ParseFromString(f.read())

    for i in reversed(range(len(graph_def.node))):
        if graph_def.node[i].op == 'Const':
            del graph_def.node[i]

    tf.train.write_graph(graph_def, "", 'graph.pbtxt', as_text=True)
```
then open `graph.pbtxt` and replace all the `AddV2` to `Add`

now it is possible to use without the mentioned patch:

```python
import cv2 as cv
import numpy as np

net = cv.dnn.readNet('MobileNetV2Alpha0.10.pb', 'graph.pbtxt')
inp = np.random.standard_normal([1, 3, 300, 450]).astype(np.float32)
net.setInput(inp)
out = net.forward()
print(out.shape)
```
out
```
(1, 3)
```

**Comment by dbacea** [comment]
@dkurt 

Thanks for the solution, it works perfectly with OpenCV 4.2.0

The script to use for converting the graph into a .pbtxt in TensorFlow 2.1 is written below, followed by a function to read and replace all occurences of the metioned string:

````
def convert_pb_to_pbtxt(path_to_pb, save_pbtxt_name, save_pbtxt_dir = '.'):
    with tf.compat.v1.gfile.FastGFile(path_to_pb, "rb") as f:
        graph_def = tf.compat.v1.GraphDef()
        graph_def.ParseFromString(f.read())

        for i in reversed(range(len(graph_def.node))):
            if graph_def.node[i].op == 'Const':
                del graph_def.node[i]

        tf.io.write_graph(graph_def, save_pbtxt_dir, save_pbtxt_name, as_text=True)
        
def replace_string_in_file(path_to_file, string_to_replace, replace_string):
    fin = open(path_to_file, "rt")
    data = fin.read()
    data = data.replace(string_to_replace, replace_string)
    fin.close()

    fin = open(path_to_file, "wt")
    fin.write(data)
    fin.close()
````

**Comment by WaterLake6** [comment]
replace "AddV2" with what? or other solution?  I has used the func convert_pb_to_pbtxt() same problem! could you help me ?

**Comment by dkurt** [comment]
@WaterLake6, issue has been solved long time ago. Please try to use newer OpenCV.

**Comment by TechMi97** [comment]
Which opencv in pip to use to download?? Am using pip install opencv-python==3.4.9.33 and still facing this problem.

**Comment by oleg3630** [comment]
I faced this problem yesterday with OpenCV 4.2.0 and the model saved by Tensorflow 1.15+.
I switched to OpenCV 4.3.0 and it loaded AddV2 operation fine.

**Comment by TechMi97** [comment]
I am asking if there is any PIP opencv python version for this fix.
