### ISSUE TITLE
Assertion failure when accessing a video file in icvExtractPattern

### ISSUE THREAD

**Issue by rgov** [opencv/opencv#17879]
##### System information (version)

- OpenCV => 4.4.0 (from git)
- Operating System / Platform => Linux
- Compiler => Clang

##### Detailed description

When I open a video file, I get this error:

```
[ERROR:0] global opencv/modules/videoio/src/cap.cpp (142) open VIDEOIO(CV_IMAGES): raised OpenCV exception:

OpenCV(4.4.0-pre) opencv/modules/videoio/src/cap_images.cpp:267: error: (-215:Assertion failed) number < max_number in function 'icvExtractPattern'
```

It doesn't *seem* harmful, as the program does continue running even though it claims to be an assertion failure. 

##### Steps to reproduce

It's hard to tell precisely which line of code generates the message but I believe I am just running:

```
    video = cv2.VideoCapture(args.video)
    video.set(cv2.CAP_PROP_POS_FRAMES, workunit[0])
    timestamp = int(video.get(cv2.CAP_PROP_POS_MSEC))
    success, frame = video.read()
```

The input is an .avi file I believe using MJPEG as the codec. I can get more info if needed. 

    Enabled backends(7, sorted by priority): FFMPEG(1000); GSTREAMER(990); INTEL_MFX(980); MSMF(970); V4L2(960); CV_IMAGES(950); CV_MJPEG(940)

##### Issue submission checklist

 - [x] I report the issue, it's not a question
   
 - [x] I checked the problem with documentation, FAQ, open issues,
       answers.opencv.org, Stack Overflow, etc and have not found solution
   
 - [ ] I updated to latest OpenCV version and the issue is still there
   
 - [ ] There is reproducer code and related data files: videos, images, onnx, etc

**Comment by alalek** [comment]
What is video file name passed to VideoCapture?

**Comment by rgov** [comment]
It is `20170922070229477.avi`.

**Comment by mshabunin** [comment]
@rgov , this is not really an issue. OpenCV tries all VideoCapture backends in specific order, `images` backend has higher priority than `mjpeg` backend, `images` backend tries to find a number in provided filename because it assumes there is a sequence of frames in multiple files, the number is there but is too big and can not be parsed, `images` backend is skipped and next one is tried.

In most cases users don't see these messages because FFmpeg and GStreamer backends can read many various formats. Perhaps we could lower the logging level to warning [here](https://github.com/opencv/opencv/blob/e65e23b9c0bc6d3d9b5bd6c55d966a774e6d3ce2/modules/videoio/src/cap.cpp#L140-L142) or change the message to reduce confusion.

**Comment by morestart** [comment]
when i use cv2 to write some frames to video, i got this error:` error: (-215:Assertion failed) number < max_number in function 'cv::icvExtractPattern'`

this is my code:
```Python
video_writer = cv2.VideoWriter(save_video_path, cv2.VideoWriter_fourcc('I', '4', '2', '0'), 25, (width, height))
video_writer.write(frame)
```

**Comment by alalek** [comment]
> this is my code

Make it reproducible and include parameters values.

**Comment by digenPrime** [comment]
I have the same error and I haven't find any solutions yet

**Comment by InterStella0** [comment]
For some reason, I get this as well but only in an async environment when I put them in a thread with `asyncio.to_thread`. Without async, I never even get this which is really frustrating as I really need asyncio here.
```python
fps = 25
width, height = 1280, 720
fourcc = cv2.VideoWriter_fourcc(*'mp4v')
def _sync_generate_videos(path):
    vidcap = cv2.VideoCapture(path)
    out = cv2.VideoWriter(filename, fourcc, fps, (width, height))
    try:
        while True:
            success, frame = vidcap.read()
            if not success:
                break
            # do stuff
            out.write(frame)
    finally:
        out.release()
        
async def function():
     for video_path in video_paths:
          coro = asyncio.to_thread(_sync_generate_videos, path)
          tasks.append(asyncio.create_task(coro))
      results = await asyncio.gather(*tasks)
asyncio.run(function())
 ```
 It generate this output 
 ```
[ERROR:4@94.288] global D:\a\opencv-python\opencv-python\opencv\modules\videoio\src\cap.cpp (597) cv::VideoWriter::open VIDEOIO(CV_IMAGES): raised OpenCV exception:

OpenCV(4.6.0) D:\a\opencv-python\opencv-python\opencv\modules\videoio\src\cap_images.cpp:267: error: (-215:Assertion failed) number < max_number in function 'cv::icvExtractPattern'
```

**Comment by asmorkalov** [comment]
Looks like the issue has been fixed in:
- https://github.com/opencv/opencv/pull/23896
- https://github.com/opencv/opencv/pull/23940

@mshabunin @rgov could you take a look?

**Comment by mshabunin** [comment]
@asmorkalov , it was not fixed, because this was not an issue originally. Scenario was as follows:
1. Build OpenCV without FFmpeg and GStreamer support
2. Create VideoCapture or VideoWriter with filename `1240723598273442.avi`
3. Internally it tries `CAP_IMAGES` backend first and it does not support more than 10 digits (or 9) in pattern, so it prints an error message and code goes to `CAP_MJPEG` backend which works. 

So there are following solutions:
1. Modify OpenCV - decrease logging level to WARN or lower for these messages (they might still be printed, but as warnings)
2. Modify user's application - e.g. disable logging via environment variable or explicitly set CAP_MJPEG backend in constructor/open method
3. Modify user's perception :smiley:  - just ignore these messages

**Comment by asmorkalov** [comment]
@mshabunin Could you work on this?
