### ISSUE TITLE
error: (-2:Unspecified error) Can't initialize GTK backend in function 'cvInitSystem'

### ISSUE THREAD

**Issue by Namburger** [opencv/opencv#18461]
##### System information (version)
- OpenCV => 3.4
- Operating System / Platform => aarch64 (debian based OS)
- Compiler => g++ 8.3.0

##### Detailed description
I have opencv as an external dependency that I compile from source like this:
```
ExternalProject_Add(opencv
  GIT_REPOSITORY https://github.com/opencv/opencv
  GIT_TAG "3.4"
  SOURCE_DIR opencv
  BINARY_DIR opencv-build
  CMAKE_ARGS
    -DCMAKE_BUILD_TYPE=RELEASE 
    -DFORCE_VTK=ON
    -DWITH_TBB=ON
    -DWITH_V4L=ON
    -DWITH_QT=OFF
    -DWITH_GTK_2_x=ON
    -DWITH_OPENGL=ON
    -DCMAKE_INSTALL_PREFIX=${CMAKE_BINARY_DIR}/opencv_install
)
set(OPENCV_INCLUDE_DIR ${CMAKE_BINARY_DIR}/opencv_install/include/)
set(OPENCV_LIBRARY_DIR ${CMAKE_BINARY_DIR}/opencv_install/lib/)
set(OPENCV_LIBRARIES opencv_imgproc opencv_core opencv_highgui opencv_video opencv_videoio opencv_imgcodecs opencv_features2d)
if(EXISTS "${CMAKE_BINARY_DIR}/opencv_install/share/OpenCV/OpenCVConfig.cmake")
    include(${CMAKE_BINARY_DIR}/opencv_install/share/OpenCV/OpenCVConfig.cmake)
    add_custom_target(rerun)
else()
    add_custom_target(rerun ${CMAKE_COMMAND} ${CMAKE_SOURCE_DIR} DEPENDS opencv)
endif()
```
Everything compiles just fine until I run the program, an error like this appears:
```
terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(3.4.12-pre) /media/sd/nam-detect/edgetpu-detection-camera/build/opencv/modules/highgui/src/window_gtk.cpp:624: error: (-2:Unspecified error) Can't initialize GTK backend in function 'cvInitSystem'

Aborted
```
libgtk2 is definitely installed:
```
$ sudo apt search libgtk2.0-dev
Sorting... Done
Full Text Search... Done
libgtk2.0-dev/eagle,now 2.24.32-3 arm64 [installed]
  development files for the GTK+ library
```

##### Steps to reproduce

This code, which used to works without issue: https://github.com/Namburger/edgetpu-detection-camera
We are only seeing this behavior on one of the system o_0

Any suggestion would be highly appreciated!

**Comment by 15927495612** [comment]
I have the same question. Did you solve the problem?

**Comment by Namburger** [comment]
@15927495612 nope, no words from the team, unfortunately :/

**Comment by 15927495612** [comment]
嘤嘤嘤~

**Comment by IstiakFahim28** [comment]
Facing same error. Please solve this  issue....

**Comment by alalek** [comment]
Check Internet about `gtk_init_check()` call failure reasons.

---

> We are only seeing this behavior on one of the system o_0

We don't help with remote investigation of problems which we are not able to reproduce on our side (because it is very time consuming and usually configuration problem without any following fix into OpenCV), but we can take a look on **the clear reason of the problem** and suggest some fix/workaround.

**Comment by cassidylinhares** [comment]
I managed to solve it by making sure when I ssh into aarch64 that I use ssh -Y user@host. This gives authorization to allow cv2.imshow() to display the window. 
[gtk_init_check error solved](https://unix.stackexchange.com/questions/94497/org-eclipse-swt-swterror-no-more-handles-gtk-init-check-failed-while-runnin )
hope that helps

**Comment by zjdx1998** [comment]
Anything update? I encounter this error when I try the cpp-examples in the WSL ubuntu. Hope you could fix it soon.

**Comment by n-gineer** [comment]
To help others, I found that my .bashrc needed to contain the following:
`export DISPLAY=:0.0`
previously, it said
`export DISPLAY=localhost:0.0`

**Comment by Wwupup** [comment]
> I managed to solve it by making sure when I ssh into aarch64 that I use ssh -Y user@host. This gives authorization to allow cv2.imshow() to display the window.
> [gtk_init_check error solved](https://unix.stackexchange.com/questions/94497/org-eclipse-swt-swterror-no-more-handles-gtk-init-check-failed-while-runnin)
> hope that helps

I solved the problem through this method. There is no GUI on the server side, so I need to comment out imshow.

**Comment by hcgfighting** [comment]
> To help others, I found that my .bashrc needed to contain the following:
> `export DISPLAY=:0.0`
> previously, it said
> `export DISPLAY=localhost:0.0`

this method is  effective

**Comment by w4w4n78** [comment]
> I managed to solve it by making sure when I ssh into aarch64 that I use ssh -Y user@host. This gives authorization to allow cv2.imshow() to display the window.
> [gtk_init_check error solved](https://unix.stackexchange.com/questions/94497/org-eclipse-swt-swterror-no-more-handles-gtk-init-check-failed-while-runnin)
> hope that helps

I tried this on Ubuntu 20.04 but still no luck

**Comment by TVI-BIZ** [comment]
So I encounter same problem.
"Can't initialize GTK backend in function 'cvInitSystem'". In my case I use Docker container and that error appears when I run OpenVino demo from docker. The problem is X11 server for the images or GUI server.You need install and run that server in Docker container. Running have to be when you start Docker container. In my case 

docker run --privileged -it -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix  -u 0 --device /dev/dri:/dev/dri  --device-cgroup-rule='c 189:* rmw' -v /dev/bus/usb:/dev/bus/usb --rm openvino/ubuntu18_dev:update_1904

may be that command have some redundant stuff but works for me.My container base on  official Intel container - https://hub.docker.com/r/openvino/ubuntu18_dev

**Comment by erdemozc** [comment]
hey guys. I am getting this error on navio2. does anyone know the solution?

**Comment by reunanen** [comment]
For what it's worth, I'm using `xvfb-run -a <my program>`.

**Comment by sourdurian** [comment]
> ashrc

where do you get that .bashrc file? when i ```nano ~/.bashrc``` i didnt see anything about display

**Comment by jbasement** [comment]
> > ashrc
> 
> where do you get that .bashrc file? when i `nano ~/.bashrc` i didnt see anything about display

For me the `export DISPLAY=localhost:0.0` also wasn't there in the .bashrc file before. Still adding `export DISPLAY=:0.0` to the end of the .bashrc file of the user calling  the software, in my case `pi`, worked fine.

**Comment by AyaNasser96** [comment]
if you're using openvino official docker for ubuntu you could follow those 2 steps:

1- at your terminal, before the docker run type 
`xhost + `

2- at docker run command add the following: 
`docker run  --"all your other tags" -e DISPLAY=$DISPLAY -v /tmp/.X11-unix: /tmp/.X11-unix "image id"

`Note: xhost + could do the job n

**Comment by HedoesnotDICE** [comment]
> To help others, I found that my .bashrc needed to contain the following: `export DISPLAY=:0.0` previously, it said `export DISPLAY=localhost:0.0`

It doesn't seem to work on my system (WSL ubuntu) ！

**Comment by scipioni** [comment]
this mapping **-v /tmp/.X11-unix:/tmp/.X11-unix** solved for me

**Comment by phelix001** [comment]
If you're running headless, you will probably get this error.
Can't initialize GTK backend in function 'cvInitSystem'

Solution :  
ssh -Y user@wherever  
I'm not sure how I will overcome this issue when running opencv as a service.  Perhaps just get rid of imshow.

**Comment by liuzihaode** [comment]
thank u, your answer  solved my problem

**Comment by olioolii** [comment]
> 
it works！

**Comment by kartikpodugu** [comment]
> I managed to solve it by making sure when I ssh into aarch64 that I use ssh -Y user@host. This gives authorization to allow cv2.imshow() to display the window. [gtk_init_check error solved](https://unix.stackexchange.com/questions/94497/org-eclipse-swt-swterror-no-more-handles-gtk-init-check-failed-while-runnin) hope that helps

I had to comment imshow() and also corresponding namedWindow() created for imshow(). Then my issue is resolved.

**Comment by sunbeam-217** [comment]
If you use SSH to connect you divice or your progress is a server ,and nowhere to display any image.So please remove the code related windows or display.for example imshow()

**Comment by anvinder** [comment]
I still have the problem. I am not doing ssh or using vnc. It's a rpi4 and the cv2.imshow function works fine if i run the script myself but when i do it via crontab or rc.local during boot then i see the error "can't initialize gtk backend in function 'cvinitsystem'"

**Comment by Nandu3219** [comment]
solve me ,for raspberrpi 4 terminal window

**Comment by rbgreenway** [comment]
My fix was to run the command:
`xhost +`
from  a terminal outside the docker container

**Comment by Nickiris** [comment]
I have solved this problem in WSL ubuntu
this may help： [https://mikailuos.com/2021/08/19/Games101/%E7%AC%AC%E9%9B%B6%E7%AF%87-WSL-Cmake-Opencv%E7%9A%84%E7%8E%AF%E5%A2%83%E6%90%AD%E5%BB%BA/](url)

**Comment by shinbehavior** [comment]
this helps me:

from host machine:
```
~/work_dir$ vim ~/.ssh/config 
1 Host 192.168.55.1                                                                                            
  2   HostName 192.168.55.1
  3   User user
  4   ForwardX11 yes
  5   ForwardX11Trusted yes
```
from ssh machine:
```
user@ubuntu:~$ cat /etc/ssh/sshd_config | grep X11
X11Forwarding yes
#X11DisplayOffset 10
X11UseLocalhost yes
#	X11Forwarding no
```

**Comment by alaingautherot** [comment]
If running docker, you may need `xhost +local:docker` like so:

`bash
xhost +local:docker \
	&& docker run -it \
       --env 'DISPLAY=$(DISPLAY)' \
       -v /tmp/.X11-unix:/tmp/.X11-unix \
        ....
`
