### ISSUE TITLE
dnn deploy.prototxt incompatible with external protobuf lib

### ISSUE THREAD

**Issue by Brainstorm67** [opencv/opencv#19145]
##### System information (version)

- OpenCV => 4.3.0
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2019, Static

##### Detailed description

We built OpenCV 4.3.0 to add the static lib to our own externals. After some conflicts between the built in Protobuf version of openCV and our own official protobuf build we wanted to use the given option to build OpenCV lib using our own external protobuf lib. 

##### Steps to reproduce

Compile openCV in static mode using a custom protobuf library. Try to use the deploy.prototxt as caffeConfigFile for the cv::dnn::readNetFromCaffe method.

##### Issue submission 

Everything builds and links great but an error happens upon usage of the dnn caffe config file deploy.prototxt given in the openCV samples.

After a bit of inquiry we found out that the protobuf version included with openCV has been "hacked" to allow specific caffe config behaviour. (at least on the last commit 4ec456f0a0993457120b916b36bde1d6df93e37b in 4.3.0 tag and modified since in 4.5)

- Why let the option to use a custom protobuf library if the one needed requires a custom modification ? What are we doing wrong here ? 
- Is there a specific version of deploy.prototxt that we should use in case of using the official protobuf library ? 

We would like to keep running with our official protobuf library AND be able to use openCV dnn at the same time if possible.

**Comment by alalek** [comment]
> 4.3.0

Outdated version.

Try latest code from master branch. At least opencv_face_detector is fixed with external protobuf.

BTW, Perhaps Caffe (or Caffe2) is not able to load `opencv_face_detector.caffemodel` too.

> let the option

"Defaults" works well. Changing options is an advanced usage with own specifics / support limitations.

> deploy.prototxt

Models compatible with Caffe framework should work with external protobuf too.

**Comment by Brainstorm67** [comment]
Hello, I updated to openCV 4.5.0 (latest) and still get the issue. Even in the latest version, the 3rd party protobuf lib is altered to work with the deploy.prototxt in question. I'll try and look at 

> BTW, Perhaps Caffe (or Caffe2) is not able to load opencv_face_detector.caffemodel too.

But right now we are stuck and not able to use at the same time a recent protobuf 'official' version and opencv face detection.

**Comment by alalek** [comment]
4.5.0 should not work because fix #19061 is not released yet and available on master branch only.

**Comment by Brainstorm67** [comment]
After trying with the current master branch it works fine, thanks a lot ^^
Do you have an idea of when the 4.5.1 will be released yet ?
