### ISSUE TITLE
Handling of 'value' in cv2.createTrackbar in Python

### ISSUE THREAD

**Issue by Xonxt** [opencv/opencv#20408]
##### System information (version)
- OpenCV == 4.5.3.56 (latest)
- Operating System / Platform => Windows 10 Pro
- Compiler => Python 3.7

##### Detailed description

After updating to the most recent version of `opencv-contrib-python`, now when creating a trackbar using 
```python
cv2.createTrackbar(TRACKBAR_NAME, WINDOW_NAME, 0, MAX_VAL, on_trackbar_foo)
```
the following warning is printed in the terminal:

```bash
[ WARN:0] global C:\Users\runneradmin\AppData\Local\Temp\pip-req-build-_xlv4eex\opencv\modules\highgui\src\window.cpp (704) cv::createTrackbar UI/Trackbar(Source@Navigation controls): Using 'value' pointer is unsafe and deprecated. Use NULL as value pointer. To fetch trackbar value setup callback
```

I'm not exactly sure what that means in the context of the Python API.

Furthermore, if I then try to dynamically change the maximum value of the trackbar like this

```python
cv2.setTrackbarMax(TRACKBAR_NAME, WINDOW_NAME, N)
```

the trackbar itself is now stuck at 0 (or whatever the minimum is set to) and cannot be moved with the mouse cursor.

This used to be fine in the previous versions. For example, it works fine in **4.5.2.52**.

##### Steps to reproduce

Just creating a trackbar in Python using a most recent version of OpenCV, e.g. in my case:
```python
import cv2
from functools import partial

def on_trackbar_class(value, param):
    param['current_class'] = int(value)
    param['CHANGED_CLASS'] = True       # signal that the class-trackbar was moved

# ...

# this gets the list of classes from the dataset metadata
# CLASSES = dataset.get_classes()
CLASSES = ["head", "left_hand", "right_hand", "right_leg", "left_leg"]

# this data is modified via the trackbar and then used elsewhere
current_class = 0 # this is passed down as a function argument from elsewhere, use '0' here for testing
trackbar_data = {'current_class': current_class}

# create window
WINDOW_NAME = "Navigation controls"
cv2.namedWindow(WINDOW_NAME, cv2.WINDOW_AUTOSIZE)

# create trackbar
TRACKBAR_NAME = 'Class'
max_classes = (len(CLASSES) - 1) if len(CLASSES) > 1 else 1
cv2.createTrackbar(TRACKBAR_NAME, WINDOW_NAME, 0, max_classes, partial(on_trackbar_class, param=trackbar_data))

# the length of the CLASSES might change at some point
# this actually happens elsewhere, but I'm putting this in the same function right here
cv2.setTrackbarMax(TRACKBAR_NAME, WINDOW_NAME, len(CLASSES) - 1) 

# keep the window opened for testing
cv2.waitKey(0)
```

##### Issue submission checklist

 - [ * ] I report the issue, it's not a question  
 - [ * ] I checked the problem with documentation, FAQ, open issues, forum.opencv.org, Stack Overflow, etc and have not found solution  
 - [ * ] I updated to latest OpenCV version and the issue is still there   
 - [ * ] There is reproducer code and related data files: videos, images, onnx, etc

**Comment by berak** [comment]
[py trackbar sample](https://docs.opencv.org/master/d9/dc8/tutorial_py_trackbar.html) comes with 4 of those warnings now,
basically only c++ folks using a nullptr don't see that.

what's the future plan here ?
the `int *value` is a bad thing (ownership/lifetime/responibility), will it be replaced by a sinple `int` in the future ?
add a fat warning [in the docs](https://docs.opencv.org/master/d7/dfc/group__highgui.html#gaf78d2155d30b728fc413803745b67a9b) that the behaviour of the value might change (but how ?)


as a remedy for python i'd propose to replace the createTrackbar() here:
https://github.com/opencv/opencv/blob/a7742d7d631b00346aed8a681e1bbc338d58651d/modules/python/src2/cv2.cpp#L2111

with some:

    int value; // also avoid a memleak ...
    if (!PyArg_ParseTuple(args, "ssiiO", &trackbar_name, &window_name, &value, &count, &on_change))
        return NULL;

    createTrackbar(trackbar_name, window_name, nullptr, count, OnChange, py_callback_info);
    setTrackbarPos(trackbar_name, window_name, value);

**Comment by imHarry404** [comment]
Using 'value' pointer is unsafe and deprecated. Use NULL as value pointer. To fetch trackbar value setup callback.

**Comment by berak** [comment]
btw, what to do about the +30 cpp  samples/tutorials using this in "unsafe and deprecated" fashion ? 
<details>
<summary>
list
</summary>
<pre> 
:: findstr /S /M createTrackbar *.cpp
camshiftdemo.cpp
connected_components.cpp
contours2.cpp
demhist.cpp
distrans.cpp
edge.cpp
ela.cpp
falsecolor.cpp
ffilldemo.cpp
fitellipse.cpp
laplace.cpp
morphology2.cpp
pca.cpp
tutorial_code\HighGUI\AddingImagesTrackbar.cpp
tutorial_code\HighGUI\BasicLinearTransformsTrackbar.cpp
tutorial_code\Histograms_Matching\calcBackProject_Demo1.cpp
tutorial_code\Histograms_Matching\calcBackProject_Demo2.cpp
tutorial_code\Histograms_Matching\MatchTemplate_Demo.cpp
tutorial_code\ImgProc\changing_contrast_brightness_image\changing_contrast_brightness_image.cpp
tutorial_code\ImgProc\Morphology_1.cpp
tutorial_code\ImgProc\Morphology_2.cpp
tutorial_code\ImgProc\Threshold.cpp
tutorial_code\ImgProc\Threshold_inRange.cpp
tutorial_code\ImgTrans\CannyDetector_Demo.cpp
tutorial_code\ImgTrans\HoughCircle_Demo.cpp
tutorial_code\ImgTrans\HoughLines_Demo.cpp
tutorial_code\ShapeDescriptors\findContours_demo.cpp
tutorial_code\ShapeDescriptors\generalContours_demo1.cpp
tutorial_code\ShapeDescriptors\generalContours_demo2.cpp
tutorial_code\ShapeDescriptors\hull_demo.cpp
tutorial_code\ShapeDescriptors\moments_demo.cpp
tutorial_code\TrackingMotion\cornerDetector_Demo.cpp
tutorial_code\TrackingMotion\cornerHarris_Demo.cpp
tutorial_code\TrackingMotion\cornerSubPix_Demo.cpp
tutorial_code\TrackingMotion\goodFeaturesToTrack_Demo.cpp
</pre></details>

**Comment by alalek** [comment]
@berak Thank you for pointing on that! We need to modify them accordingly.

**Comment by berak** [comment]
5.0 proposal:
* drop the "pointer to initial value* from `createTrackbar()`
* update python api / c++ samples according to that
* in the meantime (4.x),, please  *relax* the error msg to make it more obvious, that tis is not a "users fault" problem, 
but an "api in progress" one

**Comment by Proficus** [comment]
As a novice python developer, I still haven't been able to fix this problem. Perhaps tell me how to solve it?

**Comment by berak** [comment]
@[Proficus](https://github.com/Proficus) please just update to a more reccnt version, where it is fixed

**Comment by puccj** [comment]
I'm using OpenCV 4.8.0 and still have the same warning, is that possible? Am I doing something wrong, should I really use callback instead of value pointer or should I ignore the warning?

**Comment by dr-mrsthemonarch** [comment]
Static library compiled of mac m1, opencv 4.9.1, I also have this issue when following the tutorials for c++. I believe this should be fixed already, but it does not go away.
