### ISSUE TITLE
cap.get(CAP_PROP_POS_MSEC) return 0

### ISSUE THREAD

**Issue by AutomanHan** [opencv/opencv#20550]
Hi, all, I got a problem when using cap.get(0) to get the current time of the frame.
I use cv2.Capture to read every frame of a video, and use cap.get(CAP_PROP_POS_MSEC) get the current time for every frame. Most of the frames can be got the right time, but the last 10 frames can not. The last 10 frames return 0. Pictures of the last 10 frames can be processed normally.
opencv == 4.5.3
![image](https://user-images.githubusercontent.com/24837080/129322561-4f1d4b90-84fd-4c58-b7b1-e6e3d8c74025.png)

**Comment by asmorkalov** [comment]
Please share video, code to reproduce and information about your OpenCV build configuration (cv::getBuildInformation() call output).

**Comment by TTKuLa** [comment]
Hi all.
I'm experiencing the same problem since upgrading from opencv 4.5.1 to 4.5.5.

# Video to reproduce:
https://user-images.githubusercontent.com/99884716/154495763-d2ec6415-e940-467b-883b-544dd83cb0e4.mp4

# Code to reproduce:
Using Python 3.9.0 with `opencv-python 4.5.5.62`
```python
import cv2

filePath = r"./variable_frame_rate.mp4"

capture = cv2.VideoCapture(filePath)
idx = 0
while capture.grab():
    frameTime = capture.get(cv2.CAP_PROP_POS_MSEC)
    print(f'idx: {idx}, time: {frameTime}')
    idx += 1
capture.release()
```

## Output of the above code using `opencv-python 4.5.5.62`
```
...
idx: 94, time: 14633.711111111112
idx: 95, time: 14666.6
idx: 96, time: 14703.355555555556
idx: 97, time: 14723.244444444445
idx: 98, time: 14739.388888888889
idx: 99, time: 14809.266666666668
idx: 100, time: 14919.844444444445
idx: 101, time: 0.0
idx: 102, time: 0.0
idx: 103, time: 0.0
idx: 104, time: 0.0
idx: 105, time: 0.0
idx: 106, time: 0.0
```

## Compare with output of `opencv-python 4.5.1.48`
```
...
idx: 94, time: 14633.711111111112
idx: 95, time: 14666.6
idx: 96, time: 14703.355555555556
idx: 97, time: 14723.244444444445
idx: 98, time: 14739.388888888889
idx: 99, time: 14809.266666666668
idx: 100, time: 14919.844444444445
idx: 101, time: 14973.122222222222
idx: 102, time: 14995.18888888889
idx: 103, time: 15032.400000000001
idx: 104, time: 15074.333333333334
idx: 105, time: 15107.38888888889
idx: 106, time: 15125.077777777778
```

# OpenCV build configuration
```
General configuration for OpenCV 4.5.5 =====================================
  Version control:               4.5.5

  Platform:
    Timestamp:                   2021-12-28T06:21:01Z
    Host:
      Windows 10.0.17763 AMD64
    CMake:                       3.22.1
    CMake generator:             Visual Studio 14 2015
    CMake build tool:            MSBuild.exe
    MSVC:                        1900

Configuration:               Debug Release

  CPU/HW features:
    Baseline:                    SSE SSE2 SSE3
      requested:                 SSE3
    Dispatched code generation:  SSE4_1 SSE4_2 FP16 AVX AVX2

   requested:                 SSE4_1 SSE4_2 AVX FP16 AVX2 AVX512_SKX
      SSE4_1 (16 files):         + SSSE3 SSE4_1
      SSE4_2 (1 files):          + SSSE3 SSE4_1 POPCNT SSE4_2
      FP16 (0 files):            + SSSE3 SSE4_1 POPCNT SSE4_2 FP16 AVX
      AVX (4 files):             + SSSE3 SSE4_1 POPCNT SSE4_2 AVX
      AVX2 (31 files):           + SSSE3 SSE4_1 POPCNT SSE4_2 FP16 FMA3 AVX AVX2

  C/C++:
    Built as dynamic
libs?:      NO
    C++ standard:                11
    C++ Compiler:                C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe  (ver 19.0.24245.0)
    C++ flags (Release):         /DWIN32 /D_WINDOWS /W4 /GR  /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _SCL_SECURE_NO_WARNINGS /Gy /bigobj /Oi  /fp:precise     /EHa /wd4127 /wd4251 /wd4324 /wd4275 /wd4512 /wd4589 /MP  /MT /O2 /Ob2 /DNDEBUG 
    C++ flags (Debug):           /DWIN32 /D_WINDOWS /W4 /GR  /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _SCL_SECURE_NO_WARNINGS /Gy /bigobj /Oi  /fp:precise     /EHa /wd4127 /wd4251 /wd4324 /wd4275 /wd4512 /wd4589 /MP  /MTd /Zi /Ob0 /Od /RTC1 
    C Compiler:                  C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe
    C flags (Release):           /DWIN32 /D_WINDOWS /W3
/D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _SCL_SECURE_NO_WARNINGS /Gy /bigobj /Oi  /fp:precise     /MP   /MT /O2 /Ob2 /DNDEBUG
    C flags (Debug):             /DWIN32 /D_WINDOWS /W3  /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _SCL_SECURE_NO_WARNINGS /Gy /bigobj /Oi  /fp:precise     /MP /MTd /Zi /Ob0 /Od /RTC1 
    Linker flags (Release):      /machine:x64  /NODEFAULTLIB:atlthunk.lib /INCREMENTAL:NO  /NODEFAULTLIB:libcmtd.lib /NODEFAULTLIB:libcpmtd.lib /NODEFAULTLIB:msvcrtd.lib
    Linker flags (Debug):        /machine:x64  /NODEFAULTLIB:atlthunk.lib /debug /INCREMENTAL  /NODEFAULTLIB:libcmt.lib /NODEFAULTLIB:libcpmt.lib /NODEFAULTLIB:msvcrt.lib
    ccache:                      NO
    Precompiled headers:         YES
    Extra dependencies:          wsock32 comctl32 gdi32 ole32 setupapi ws2_32
    3rdparty dependencies:       libprotobuf ade ittnotify libjpeg-turbo libwebp libpng libtiff libopenjp2 IlmImf zlib quirc ippiw ippicv

  OpenCV modules:
    To be built:                 calib3d core dnn features2d flann gapi highgui imgcodecs imgproc ml objdetect photo python3 stitching video videoio
    Disabled:                    world
    Disabled by dependency:      -
    Unavailable:                 java python2 ts
    Applications:
         -
    Documentation:               NO
    Non-free algorithms:         NO

  Windows RT support:            NO

  GUI:                           WIN32UI
    Win32 UI:                    YES
    VTK support:                 NO

  Media I/O:
    ZLib:                        build (ver 1.2.11)
    JPEG:                        build-libjpeg-turbo (ver 2.1.2-62)
    WEBP:                        build (ver encoder:
0x020f)
    PNG:                         build (ver 1.6.37)
    TIFF:                        build (ver 42 - 4.2.0)
    JPEG 2000:                   build (ver 2.4.0)
    OpenEXR:                     build (ver 2.3.0)
    HDR:                         YES
    SUNRASTER:                   YES
    PXM:                         YES
    PFM:                         YES

  Video I/O:
    DC1394:                      NO
    FFMPEG:                      YES (prebuilt binaries)
      avcodec:                   YES (58.134.100)
      avformat:                  YES (58.76.100)
      avutil:                    YES (56.70.100)
      swscale:
                YES (5.9.100)
      avresample:                YES (4.0.0)
    GStreamer:                   NO
    DirectShow:                  YES
    Media Foundation:            YES
      DXVA:
     YES

  Parallel framework:            Concurrency

  Trace:                         YES (with Intel ITT)

  Other third-party libraries:
    Intel IPP:                   2020.0.0 Gold [2020.0.0]

 at:                   D:/a/opencv-python/opencv-python/_skbuild/win-amd64-3.6/cmake-build/3rdparty/ippicv/ippicv_win/icv
    Intel IPP IW:                sources (2020.0.0)
              at:                D:/a/opencv-python/opencv-python/_skbuild/win-amd64-3.6/cmake-build/3rdparty/ippicv/ippicv_win/iw
    Lapack:                      NO
    Eigen:                       NO
    Custom HAL:                  NO
    Protobuf:
                build (3.19.1)

  OpenCL:                        YES (NVD3D11)
    Include path:                D:/a/opencv-python/opencv-python/opencv/3rdparty/include/opencl/1.2
    Link libraries:              Dynamic load

  Python 3:
    Interpreter:                 C:/hostedtoolcache/windows/Python/3.6.8/x64/python.exe (ver 3.6.8)
    Libraries:                   C:/hostedtoolcache/windows/Python/3.6.8/x64/libs/python36.lib (ver 3.6.8)
    numpy:                       C:/hostedtoolcache/windows/Python/3.6.8/x64/lib/site-packages/numpy/core/include (ver 1.13.3)
    install path:                python/cv2/python-3

  Python (for build):            C:/hostedtoolcache/windows/Python/2.7.18/x64/python.exe

  Java:
    ant:                         NO
    JNI:                         C:/hostedtoolcache/windows/Java_Temurin-Hotspot_jdk/8.0.312-7/x64/include C:/hostedtoolcache/windows/Java_Temurin-Hotspot_jdk/8.0.312-7/x64/include/win32 C:/hostedtoolcache/windows/Java_Temurin-Hotspot_jdk/8.0.312-7/x64/include
    Java wrappers:
        NO
    Java tests:                  NO

  Install to:                    D:/a/opencv-python/opencv-python/_skbuild/win-amd64-3.6/cmake-install
-----------------------------------------------------------------
```

**Comment by asmorkalov** [comment]
@TTKuLa Your OpenCV instance is built with several videoio back-ends and it's not clear where there problem is. Could you run the repro with `OPENCV_VIDEOIO_DEBUG=1` environment option and share the program output. The option enables internal debug logs in VideoCapture. See https://docs.opencv.org/4.x/de/db1/group__videoio__registry.html for details.

**Comment by TTKuLa** [comment]
@asmorkalov Running with `OPENCV_VIDEOIO_DEBUG=1` gives the following output:

```
[ WARN:0@0.135] global D:\a\opencv-python\opencv-python\opencv\modules\videoio\src\cap.cpp (132) cv::VideoCapture::open VIDEOIO(FFMPEG): trying capture filename='./variable_frame_rate.mp4' ...
[ WARN:0@0.154] global D:\a\opencv-python\opencv-python\opencv\modules\videoio\src\cap.cpp (144) cv::VideoCapture::open VIDEOIO(FFMPEG): created, isOpened=1
idx: 0, time: 0.0
idx: 1, time: 726.4777777777778
idx: 2, time: 759.0444444444445
idx: 3, time: 802.9555555555556
idx: 4, time: 842.3333333333334
idx: 5, time: 859.7
idx: 6, time: 965.7555555555556
idx: 7, time: 976.1
idx: 8, time: 1068.6222222222223
idx: 9, time: 1194.1000000000001
idx: 10, time: 1228.8666666666668
idx: 11, time: 1258.4222222222224
idx: 12, time: 1280.3666666666666
idx: 13, time: 1327.0111111111112
idx: 14, time: 1361.6000000000001
idx: 15, time: 1392.4333333333334
idx: 16, time: 1458.9444444444446
idx: 17, time: 1493.9555555555557
idx: 18, time: 1511.1555555555556
idx: 19, time: 1559.1444444444444
idx: 20, time: 1629.0777777777778
idx: 21, time: 1695.6222222222223
idx: 22, time: 1709.1333333333334
idx: 23, time: 5529.533333333333
idx: 24, time: 5580.088888888889
idx: 25, time: 5612.966666666667
idx: 26, time: 5679.811111111111
idx: 27, time: 5698.111111111111
idx: 28, time: 5764.788888888889
idx: 29, time: 5829.855555555556
idx: 30, time: 5904.566666666667
idx: 31, time: 6004.866666666667
idx: 32, time: 6030.222222222222
idx: 33, time: 6064.7
idx: 34, time: 6098.722222222223
idx: 35, time: 6123.9
idx: 36, time: 6164.277777777778
idx: 37, time: 6182.111111111111
idx: 38, time: 6197.588888888889
idx: 39, time: 6265.5666666666675
idx: 40, time: 6317.611111111111
idx: 41, time: 6346.766666666667
idx: 42, time: 6402.744444444445
idx: 43, time: 6414.900000000001
idx: 44, time: 6463.922222222222
idx: 45, time: 9069.155555555555
idx: 46, time: 9117.21111111111
idx: 47, time: 9169.222222222223
idx: 48, time: 9200.5
idx: 49, time: 9217.222222222223
idx: 50, time: 9282.222222222223
idx: 51, time: 9301.1
idx: 52, time: 9362.0
idx: 53, time: 9384.077777777778
idx: 54, time: 9418.144444444446
idx: 55, time: 9443.166666666666
idx: 56, time: 9452.055555555557
idx: 57, time: 9483.833333333334
idx: 58, time: 9566.922222222223
idx: 59, time: 9588.08888888889
idx: 60, time: 9634.422222222223
idx: 61, time: 9668.233333333334
idx: 62, time: 9700.555555555557
idx: 63, time: 9717.766666666668
idx: 64, time: 9752.6
idx: 65, time: 9768.977777777778
idx: 66, time: 9801.033333333335
idx: 67, time: 9818.900000000001
idx: 68, time: 9850.211111111112
idx: 69, time: 9887.033333333333
idx: 70, time: 9968.522222222224
idx: 71, time: 10000.233333333334
idx: 72, time: 10033.166666666666
idx: 73, time: 10051.377777777778
idx: 74, time: 10084.955555555556
idx: 75, time: 10120.866666666669
idx: 76, time: 10133.955555555556
idx: 77, time: 10167.655555555555
idx: 78, time: 13675.033333333333
idx: 79, time: 13722.011111111111
idx: 80, time: 13755.37777777778
idx: 81, time: 13781.644444444446
idx: 82, time: 13828.566666666668
idx: 83, time: 13899.566666666668
idx: 84, time: 13960.055555555557
idx: 85, time: 13989.311111111112
idx: 86, time: 14072.566666666668
idx: 87, time: 14104.877777777778
idx: 88, time: 14172.322222222223
idx: 89, time: 14205.566666666668
idx: 90, time: 14238.377777777778
idx: 91, time: 14506.88888888889
idx: 92, time: 14539.177777777779
idx: 93, time: 14573.911111111112
idx: 94, time: 14633.711111111112
idx: 95, time: 14666.6
idx: 96, time: 14703.355555555556
idx: 97, time: 14723.244444444445
idx: 98, time: 14739.388888888889
idx: 99, time: 14809.266666666668
idx: 100, time: 14919.844444444445
idx: 101, time: 0.0
idx: 102, time: 0.0
idx: 103, time: 0.0
idx: 104, time: 0.0
idx: 105, time: 0.0
idx: 106, time: 0.0
```

**Comment by wuhongsheng** [comment]
+1

**Comment by asmorkalov** [comment]
Looks like the issue is fixed in https://github.com/opencv/opencv/pull/22145. Could you try OpenCV build from current 4.x and report new status here.

**Comment by TTKuLa** [comment]
I tried reproducing it with `opencv-python-rolling 4.6.0.20221022`. Calling `cv2.getBuildInformation()` returns `4.6.0-474-g23edec83fb`. The fix should be included here, however the output is still the same as before.

**Comment by Mscht** [comment]
Hello @asmorkalov,
Please note that this issue is still not fixed. This is a major problem for us, as we have to stick to `4.5.1.48` without support for Python 3.10.
I tried `opencv-python-rolling 4.6.0.20221217`. I tried both the video of this issue and the video of https://github.com/opencv/opencv/issues/22141. I expect the fix to be included in this build, am I right?
Can you please double check the solution?
Thank you and merry christmas!

**Comment by Mscht** [comment]
I'm happy to confirm that this issue is fixed in opencv-python `4.7.0.68`. Thank you for you work.

**Comment by matanster** [comment]
I have it that ` cap.get(CAP_PROP_POS_MSEC) ` always returns -1 on Windows 11, with opencv-python-4.5.5.62. Hope to be testing it on a Windows 11 machine with the latest opencv soon.
