### ISSUE TITLE
Unknown Exception when loading an onnx model

### ISSUE THREAD

**Issue by ziywang50** [opencv/opencv#22326]
##### System information (version)

- OpenCV => :grey_question:
- Operating System / Platform => :grey_question:
- Compiler => :grey_question:

##### Detailed description

This model can be loaded from another computer, but in this computer it gives an error:  Microsoft C++ exception: cv::Exception at memory location 0x0000009CF5190F30. Can somebody help me to debug?

**Comment by ziywang50** [comment]
opencv >= 4.5.0
operating system windows 64 bit
compiler: vs 2019

**Comment by asmorkalov** [comment]
Could you share the model and piece of code to reproduce the issue. The provided information is not enough for the issue debugging.

**Comment by ziywang50** [comment]
[yolo.zip](https://github.com/opencv/opencv/files/9260242/yolo.zip)

**Comment by ziywang50** [comment]
This file contains two folders. I created a vs project and included everything in code.zip

**Comment by ziywang50** [comment]
The onnx model is in the InferYolodata folder

**Comment by zihaomu** [comment]
Hi @ziywang50, I have tested your model, and it works well on my machine. Please check that the correct path is used.

**Comment by ziywang50** [comment]
I double checked that the path works.

**Comment by zihaomu** [comment]
Hi @ziywang50, can it work?

**Comment by ziywang50** [comment]
![image](https://user-images.githubusercontent.com/38633841/183802196-607ec08b-a116-48c1-814f-ae4d171a9dc9.png)

**Comment by ziywang50** [comment]
I tested with another computer it works, just not this computer

**Comment by ziywang50** [comment]
It's the same error.

**Comment by ziywang50** [comment]
I am not sure if memory is a problem. My computer has 8g memory but only <4g can use

**Comment by zihaomu** [comment]
This error is not the same as the one below, right?

> Microsoft C++ exception: cv::Exception at memory location 0x0000009CF5190F30.

From the image you attached, this error is because we are not supporting the ONNX unsqueeze layer of the opset13 version. 
The PR of opset 13 of unsqueeze is under code reviewing, #22306.
As a workaround, you can try to export ONNX models of `opset_version` lower than version 13.
Something like the following ([link](https://pytorch.org/tutorials/advanced/super_resolution_with_onnxruntime.html)):
```py
# Input to the model
x = torch.randn(batch_size, 1, 224, 224, requires_grad=True)
torch_out = torch_model(x)

# Export the model
torch.onnx.export(torch_model,               # model being run
                  x,                         # model input (or a tuple for multiple inputs)
                  "super_resolution.onnx",   # where to save the model (can be a file or file-like object)
                  export_params=True,        # store the trained parameter weights inside the model file
                  opset_version=10,          # the ONNX version to export the model to
                  do_constant_folding=True,  # whether to execute constant folding for optimization
                  input_names = ['input'],   # the model's input names
                  output_names = ['output'], # the model's output names
                  dynamic_axes={'input' : {0 : 'batch_size'},    # variable length axes
                                'output' : {0 : 'batch_size'}})
```

**Comment by ziywang50** [comment]
Two errors. One error is the image I attached, the second is the Microsoft c++ exception

**Comment by ziywang50** [comment]
Exception thrown at 0x00007FF996C04FD9 in Project2.exe: Microsoft C++ exception: cv::Exception at memory location 0x0000002D45FF1260.
Exception thrown at 0x00007FF996C04FD9 in Project2.exe: Microsoft C++ exception: cv::Exception at memory location 0x0000002D45FEECF0.

**Comment by zihaomu** [comment]
Can the unsqueeze error be fixed by my comment?

**Comment by ziywang50** [comment]
I am asking my colleague. This model is trained by her so I have not fixed it right now.

**Comment by ziywang50** [comment]
Is it possible to directly convert an opset 13 to opset 12 without training？

**Comment by ziywang50** [comment]
[ INFO:0] global C:\build\master_winpack-build-win64-vc14\opencv\modules\dnn\src\onnx\onnx_importer.cpp (429) cv::dnn::d
nn4_v20210608::ONNXImporter::populateNet DNN/ONNX: loading ONNX v7 model produced by 'pytorch':1.12.1. Number of nodes =
 259, inputs = 1, outputs = 1
OpenCV(4.5.3) Error: Assertion failed (inputs.size()) in cv::dnn::dnn4_v20210608::Layer::getMemoryShapes, file C:\build\
master_winpack-build-win64-vc14\opencv\modules\dnn\src\dnn.cpp, line 5298
[ERROR:0] global C:\build\master_winpack-build-win64-vc14\opencv\modules\dnn\src\onnx\onnx_importer.cpp (2127) cv::dnn::
dnn4_v20210608::ONNXImporter::handleNode DNN/ONNX: ERROR during processing node with 1 inputs and 1 outputs: [Identity]:
(onnx::Reshape_475)
[ INFO:0] global C:\build\master_winpack-build-win64-vc14\opencv\modules\dnn\src\onnx\onnx_importer.cpp (2131) cv::dnn::
dnn4_v20210608::ONNXImporter::handleNode     Input[0] = 'onnx::Reshape_455'
[ INFO:0] global C:\build\master_winpack-build-win64-vc14\opencv\modules\dnn\src\onnx\onnx_importer.cpp (2135) cv::dnn::
dnn4_v20210608::ONNXImporter::handleNode     Output[0] = 'onnx::Reshape_475'
OpenCV(4.5.3) Error: Unspecified error (> Node [Identity]:(onnx::Reshape_475) parse error: OpenCV(4.5.3) C:\build\master
_winpack-build-win64-vc14\opencv\modules\dnn\src\dnn.cpp:5298: error: (-215:Assertion failed) inputs.size() in function
'cv::dnn::dnn4_v20210608::Layer::getMemoryShapes'
> ) in cv::dnn::dnn4_v20210608::ONNXImporter::handleNode, file C:\build\master_winpack-build-win64-vc14\opencv\modules\d
nn\src\onnx\onnx_importer.cpp, line 2146

C:\Users\ziywa\Desktop\aubo-robotics\yolo\Project2\x64\Debug\Project2.exe (process 19692) exited with code -1.
To automatically close the console when debugging stops, enable Tools->Options->Debugging->Automatically close the conso
le when debugging stops.
Press any key to close this window . . .

Same problem. I downloaded a model from the yolov5 website and then exported using the export script with opset = 12. I still got this error.

**Comment by ziywang50** [comment]
Also this error: Microsoft C++ exception: cv::Exception at memory location 0x00000037AB7BE8F0.

**Comment by zihaomu** [comment]
Hi @ziywang50, can you attach the model file?

**Comment by ziywang50** [comment]
I am pretty sure it is the problem with my computer. Not sure why. I just called cv::dnn::readNet

**Comment by zihaomu** [comment]
Which CPU do you use?

**Comment by ziywang50** [comment]
[Uploading yolov5s.zip…]()
CPU is Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz   1.99 GHz

**Comment by zihaomu** [comment]
Model link error.

**Comment by ziywang50** [comment]
yes, because it is still uploading

**Comment by ziywang50** [comment]
I also uploaded it in my repository

**Comment by ziywang50** [comment]
https://github.com/ziywang50/onnx-model-trained-from-yolov5

**Comment by zihaomu** [comment]
Hi, @ziywang50, I have checked the yolov5 model, it can not be loaded on my site. But after the optimization with `onnxsim`, it can work well.
```py
import onnx
import onnxsim
import numpy as np  # type: ignore

path = "yolov5s.onnx"
models_files = "yolov5s-sim.onnx"
onnx_model = onnx.load(path)
input_shape = np.array([1, 3, 640, 640])
input = dict()
input["images"] = input_shape
out = onnxsim.simplify(onnx_model, dynamic_input_shape=True, input_shapes=input)

onnx.save(out[0], models_files)
```

**Comment by zihaomu** [comment]
After `onnxsim`, [yolov5s-sim.onnx.zip](https://github.com/opencv/opencv/files/9334999/yolov5s-sim.onnx.zip) works well.

**Comment by ziywang50** [comment]
yes, but not on mine.

**Comment by ziywang50** [comment]
But it gave "read net ok" so I think readNet works fine

**Comment by ziywang50** [comment]
yes, readNet works fine now
