### ISSUE TITLE
cv2.distanceTransform() crashes on large images

### ISSUE THREAD

**Issue by Tetane** [opencv/opencv#23895]
### System Information

OpenCV python version: 4.7.0.72
OS: Windows 10
Python version: 3.10.11
RAM: 128Go

### Detailed description

cv2.distanceTransform() raises an exception `cv2.error: Unknown C++ exception from OpenCV code` when I try to use it with an image of size `50000*50000`. And sometimes even crash without any exception with slightly bigger images.
It works for an image of size `45000*45000`. I don't know the exact number of pixels where it starts to fail.

I also tried setting the environment variable:
```
import os
os.environ["CV_IO_MAX_IMAGE_PIXELS"] = f"{2**63}"
import cv2 as cv
```

### Steps to reproduce

`testDist = cv.distanceTransform(testImg, cv.DIST_L2, cv.DIST_MASK_3)`
with `testImg` being a `numpy ndarray` of type `uint8` and shape `[50000, 50000]`

### Issue submission checklist

- [X] I report the issue, it's not a question
- [X] I checked the problem with documentation, FAQ, open issues, forum.opencv.org, Stack Overflow, etc and have not found any solution
- [X] I updated to the latest OpenCV version and the issue is still there
- [X] There is reproducer code and related data files (videos, images, onnx, etc)

**Comment by asmorkalov** [comment]
Most probably the issue has bin fixed in https://github.com/opencv/opencv/issues/22732 and was released in 4.8.0 couple of days ago. Python packages wil be ready in a couple of days.

**Comment by Tetane** [comment]
Ok, thanks for the answer, I will test with the new version when it comes out.

**Comment by Tetane** [comment]
I updated opencv-python to version 4.8.0.74 and I still have the same issue.
The program still crashes if I use `DIST_MASK_3` or `DIST_MASK_5`.
If I use `DIST_MASK_PRECISE` it does not crash but there are artifacts at the bottom of the image:
![opencv_dist_bug](https://github.com/opencv/opencv/assets/13542748/cf226429-c089-4507-81ce-dba1a595aa07)

The row of pixels where the artifacts start is not always the same and depends on the size of the image. For the image above of size `52648, 52170`, the artifacts start at row `46799`. If the image is less wide, sometimes there are no artifacts at the bottom, the pixels are just black after a certain row number.

**Comment by dkurt** [comment]
Hi, @Tetane! Can you please verify if the following patch solves the problem https://github.com/opencv/opencv/pull/24214?

**Comment by Tetane** [comment]
I compiled OpenCV from source to test this new PR. My version is: 4.8.0-195-g178fdbbda8
I tested `cv::distanceTransform` on a `70000*70000` image with `distanceType = DIST_L2` and `maskSize` = `DIST_MASK_PRECISE` `DIST_MASK_3` and `DIST_MASK_5` (and `dstType = CV_32F`).

`DIST_MASK_PRECISE` still show some artifacts which makes the image unusable.

`DIST_MASK_3` doesn't crash anymore but the maximum value of the distance is `8192`.

`DIST_MASK_5` crashes in `distransform.cpp` on line `827` 
```
Unhandled exception at 0x00007FFED3D3EE49 (opencv_imgproc480d.dll) in test_opencv1.exe: 0xC0000005: Access violation reading location 0x000001C597005FFC.
```

**Comment by dkurt** [comment]
@Tetane, Thanks! Can you please provide some C++ reproducer to catch the artifacts?

**Comment by Tetane** [comment]
Here is the code I used for the tests:
(for the image I use the "stuff.jpg" image in  `opencv/samples/data`)
```C++
#include "opencv2/core/utility.hpp"
#include "opencv2/imgproc.hpp"
#include "opencv2/imgcodecs.hpp"

#include <iostream>
#include <stdio.h>

int main( int argc, const char** argv )
{
    cv::Mat gray = cv::imread("stuff.jpg", cv::ImreadModes::IMREAD_GRAYSCALE);

    cv::Mat gray_resize;
    cv::resize(gray, gray_resize, cv::Size(70000,70000), 0.0, 0.0, cv::INTER_LINEAR);

    gray_resize = gray_resize >= 100;

    cv::Mat dist;
    cv::distanceTransform(gray_resize, dist, cv::DIST_L2, cv::DIST_MASK_PRECISE, CV_32F);

    cv::Mat dist_resize;
    cv::resize(dist, dist_resize, cv::Size(25000,25000), 0.0, 0.0, cv::INTER_LINEAR);

    cv::String outfilePath = "C:/Users/aaaaa/Documents/OpenCV/test_opencv/out_data/test_mask_precise.tif";
    cv::imwrite(outfilePath, dist_resize);

    std::cout << std::endl << cv::getBuildInformation() << std::endl;

    return 0;
}
```

With this code, the resulting image looks like this:
![Capture d’écran 2023-09-06 130126](https://github.com/opencv/opencv/assets/13542748/d4814d33-128f-4cd3-b311-4ae50540d37f)

**Comment by dkurt** [comment]
@Tetane, can you please verify the latest version of PR https://github.com/opencv/opencv/pull/24234?

**Comment by dkurt** [comment]
@Tetane, maximum distance of `65536` is a limitation of current implementation based on unsigned integers and the fact that 65536*65536 > UINT_MAX (2^32 - 1). So this is an infinity marker. Does your task require bigger distances?

>  In distransform.cpp on line 846:

Oh, that's IPP part. I have not covered it yet. So my setup was `-DWITH_IPP=OFF`

**Comment by Tetane** [comment]
@dkurt Ok. I work with pretty big rasters, but a distance above `65536` should not happen very often in real case scenarios, and even if it does I think I can find some workarounds.

Thank you very much for your work on this issue!

**Comment by dkurt** [comment]
Exact exception from https://github.com/opencv/opencv/issues/23895#issuecomment-1707885981 :

```
OpenCV(4.8.0-dev) Error: Assertion failed (udata < (uchar*)ptr && ((uchar*)ptr - udata) <= (ptrdiff_t)(sizeof(void*)+64)) in fastFree, file /home/dkurtaev/opencv/modules/core/src/alloc.cpp, line 191
terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(4.8.0-dev) /home/dkurtaev/opencv/modules/core/src/alloc.cpp:191: error: (-215:Assertion failed) udata < (uchar*)ptr && ((uchar*)ptr - udata) <= (ptrdiff_t)(sizeof(void*)+64) in function 'fastFree'
```

**Comment by dkurt** [comment]
> DIST_MASK_5 crashes in distransform.cpp on line 827

@Tetane, issue with IPP version on large Mat solved by https://github.com/opencv/opencv/pull/24535 (now fallbacks to C++ implementation).
