### ISSUE TITLE
`_InputArray` and its derivatives need a clean-up

### ISSUE THREAD

**Issue by cjdb** [opencv/opencv#26289]
### System Information

All systems.

### Detailed description

`_InputArray` and its derivatives have different behaviour based on what kind of "container" they hold. The code makes many mistakes about how C++'s memory model works, which ultimately leads to tcmalloc crashes when testing a `std::vector` optimisation that I've been working on for libc++.

For example, the following snippet simultaneously treats `obj` as `std::vector<uchar>*` and `std::vector<Vec2b>*` when `esz == 2`, which is impossible: `obj` can only be one of these types at a time.

```cpp
CV_Assert(!fixedSize() || len == ((std::vector<uchar>*)v)->size() / esz);
switch( esz )
{
case 1:
  ((std::vector<uchar>*)v)->resize(len);
  break;
case 2:
  ((std::vector<Vec2b>*)v)->resize(len);
  break;
```

Further, `_InputArray` can hold vectors of vectors of many types, but this section only seems to handle `vector<vector<uchar>>`.
-----
The crashes that I see are because OpenCV is erasing `vector<T>` to `vector<uchar>`. Up until now, `std::vector` has been implemented using three pointers (one that points to the beginning of the buffer, one that points to where the next element should be inserted, and one that acts as a sentinel for reallocation). This implementation stores where the allocated memory is starts and ends, allowing OpenCV's type punning to accidentally work.

I'm working on a patch to `std::vector` that redesigns it to use one pointer and two integers (one for the size and capacity, respectively). This means that the end boundary needs to be computed by `std::vector` during deallocation and since we're working `uchar`---which is smaller than the original type---the boundary calculation is substantially smaller than it should be. tcmalloc notices this, and forces a crash.

@zygoloid suggested having `_InputArray` store a pointer to a global object that dispatches to the member functions that implement the behaviour with the correct types. E.g.
```cpp
struct _InputArrayOps {
  virtual Mat getMat_(void* data, int idx) = 0;
  // ... other operations ...
};

// _InputArray operations for const std::vector<T>&
template<typename T> struct _InputArrayOps_vector : _InputArrayOps {
  Mat getMat_(void* data, int idx) override {
    CV_Assert( idx < 0 );
    std::vector<T>& v = *static_cast<std::vector<T>*>(data);
    return !v.empty() ? Mat(v.size(), traits::Type<T>::value + ACCESS_READ, (void*)v.data()) : Mat();
  }
  // ... other operations ...
};
template<typename T> constexpr inline _InputArrayOps_vector<T> _InputArrayOps_vector_instance;

// ... other supported types ...

class _InputArray {
public:
  // ...
  template<typename T> _InputArray(const std::vector<_Tp>& vec)
    : data(&vec), ops(&_InputArrayOps_vector_instance<T>) {}
  // ...
  Mat getMat_(int idx = -1) const { return ops->getMat_(data, idx); }
  // ...
private:
  void *data;
  _InputArrayOps *ops;
};
```

I'm working on a prototype to see how this works with my new vector representation.

### Steps to reproduce

I can't provide steps to repro just yet, but will work with you until we can get something.

### Issue submission checklist

- [X] I report the issue, it's not a question
- [X] I checked the problem with documentation, FAQ, open issues, forum.opencv.org, Stack Overflow, etc and have not found any solution
- [X] I updated to the latest OpenCV version and the issue is still there
- [ ] There is reproducer code and related data files (videos, images, onnx, etc)

**Comment by arjunMitmanipal** [comment]
can you please specify the work of _InputArray ?

**Comment by vpisarev** [comment]
@cjdb, please, take a look at #26408. It should fix the problem with the new `std::vector<T>` implementation without introducing `_InputArrayOps`.

**Comment by cjdb** [comment]
> @cjdb, please, take a look at #26408. It should fix the problem with the use of various instances of `std::vector<T>` and `std::vector<std::vector<T>>` in OpenCV. I did it without introducing `_InputArrayOps`.

Thanks for taking a stab at this @vpisarev. I'll confirm whether or not the problem is solved on Monday. A quick skim over the code tells me that `_InputArrayOps` might still be worth entertaining, but I'll need to compare our respective solutions side-by-side before recommending that (also something for Monday).

**Comment by cjdb** [comment]
@vpisarev I'm still seeing tcmalloc failures with #26408 applied. I'm going to make a draft PR in an hour or so, which has my `_InputArrayOps` approach. There are still some test failures (and possibly some outdated code due to not syncing before making my changes), but I'm hopeful that it will be informative, and helpful in setting a course that will remove the root causes of this issue.

**Comment by vpisarev** [comment]
@cjdb, I see. Unfortunately, your patch currently does not pass CI, there are even merge conflicts. And without a sample that reproduces the problem it's hard to debug my solution. It looks like we stuck, at least for OpenCV 5.0-alpha. Maybe for the beta we will finally come up with some solution. One of the key things we will be looking at is efficiency. Most of the time (in the case of Python bindings nearly 100% of the time) InputArray is used to wrap cv::Mat (which in its turn wraps Python's numpy array in the case of bindings). Normal std::vector (not a vector of vectors) is another more or less popular case (10x less popular than cv::Mat, but still). We want to be sure that if we integrate your solution, it should not bring any extra overhead compared to what we already have.

**Comment by cjdb** [comment]
> @cjdb, I see. Unfortunately, your patch currently does not pass CI, there are even merge conflicts. And without a sample that reproduces the problem it's hard to debug my solution. It looks like we stuck, at least for OpenCV 5.0-alpha. Maybe for the beta we will finally come up with some solution. One of the key things we will be looking at is efficiency. Most of the time (in the case of Python bindings nearly 100% of the time) InputArray is used to wrap cv::Mat (which in its turn wraps Python's numpy array in the case of the bindings). Normal std::vector (not a vector of vectors) is another more or less popular case (10x less popular than cv::Mat, but still). We want to be sure that if we integrate your solution, it should not bring any extra overhead compared to what we already have.

I've closed #26423 to work on a new iteration of my patch, which will probably only target `std::vector` (and pave the way for possible extensions down the line). It'll also be applied to the correct branch. Thank you for your patience!

**Comment by akchaud5** [comment]
Proposed fix for the std::vector punning in _InputArray/_OutputArray (per #26289).

Problem: _InputArray/_OutputArray erased std::vector<T> to std::vector<uchar> and type‑punned size/data/resize. This relies on legacy libstdc++/libc++ vector header layouts. New libc++ vector representation (1 pointer + 2 ints) breaks this assumption and can trigger allocator boundary crashes (e.g., tcmalloc), as described.

Approach: Implement internal, type‑safe ops for std::vector<T> and std::vector<std::vector<T>> and register them at construction. matrix_wrap.cpp now queries ops for size/data/resize instead of punning headers. This mirrors the suggestion to dispatch via type-aware operations without changing _InputArray ABI.

New helpers/registry:
modules/core/include/opencv2/core/detail/input_array_ops.hpp
modules/core/src/input_array_ops_registry.cpp
Registration in wrappers:
modules/core/include/opencv2/core/mat.inl.hpp
Refactor uses of STD_VECTOR/STD_VECTOR_VECTOR:
modules/core/src/matrix_wrap.cpp
Compatibility/perf:

No ABI/layout change to _InputArray.
Thread‑local registry keyed by the container address; minimal overhead (pointer lookup).
Fallback kept in one legacy path if ops are not present.
Patch/PR:

Branch: core-inputarray-vector-ops-26289-clean
@vpisarev would really appreciate a review of the PR.

**Comment by asmorkalov** [comment]
https://discourse.llvm.org/t/adding-a-size-based-vector-to-libc-s-unstable-abi/86306

**Comment by cjdb** [comment]
Steps to build size-based vector:

1. Install Docker.
2. Clone LLVM
```
git clone https://github.com/llvm/llvm-project.git
```
3. Patch https://github.com/llvm/llvm-project/pull/155330 into your LLVM clone. If you're have merge or rebase conflicts, checkout 94c384c9eeed, which is the revision I've rebased against right now.
```
cd llvm-project
curl https://github.com/llvm/llvm-project/pull/155330.patch | patch -p1
# git checkout e8cc0d22073f # if necessary
```
4. Run `libcxx/utils/ci/run-buildbot-container`. This will open an interactive Docker instance.
5. Run the following inside the Docker container.
```
export CC=/usr/bin/clang-21 CXX=/usr/bin/clang++-21
libcxx/utils/ci/run-buildbot generic-abi-unstable
```
6. All going well, you should have a copy of libc++ built in `/llvm/build/generic-abi-unstable`. `libcxx/gdb/gdb_pretty_printer_test.sh.cpp` fails, but that's only a concern if you need debugger support. We can ignore it for now. Install it by running the following:
```
ninja -C /llvm/build/generic-abi-unstable install
```
7. Run the following to test that you can build something with your new libc++.
```
$ export LIBCXX_INSTALL=/llvm/build/generic-abi-unstable/install
$ export CXXFLAGS="-nostdinc++ -isystem $LIBCXX_INSTALL/include/c++/v1 -nostdlib++"
$ export LDFLAGS="-L $LIBCXX_INSTALL/lib -lc++ -Wl,-rpath,$LIBCXX_INSTALL/lib"
$ cat <<EOF > test.cpp
#include <print>

int main()
{
  std::println("Hello, world!");
}
EOF
$ $CXX $CXXFLAGS $LDFLAGS -std=c++23 test.cpp -o test
$ ./test
Hello, world!
$ cat <<EOF > test.cpp
// This test fails to compile. The error message confirms that size-based
// vector is the active vector implementation.
#include <type_traits>
#include <vector>

static_assert(std::is_same_v<
  std::__vector_layout<std::vector<int>, int, std::allocator<int>>::__size_,
  void
>);
EOF
$ $CXX $CXXFLAGS $LDFLAGS -std=c++17 test.cpp
test.cpp:6:69: error: invalid use of non-static data member '__size_'
    6 |   std::__vector_layout<std::vector<int>, int, std::allocator<int>>::__size_,
      |   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~
test.cpp:6:69: error: '__size_' is a private member of 'std::__vector_layout<std::vector<int>, int, std::allocator<int>>'
/llvm/build/generic-abi-unstable/install/include/c++/v1/__vector/vector.h:228:13: note: declared private here
  228 |   size_type __size_ = 0;
      |             ^
2 errors generated.
```

You can choose to either set your OpenCV development environment up in the Docker image, or you can copy the environment variables out of Docker. You'll need to prepend the path to your `llvm-project` checkout to `LIBCXX_INSTALL`.

**Comment by cjdb** [comment]
It may be worth watching [this presentation](https://youtu.be/RKdkHwbgXfY) for additional insight into the RFC @asmorkalov linked.

**Comment by asmorkalov** [comment]
Fixed in 4.x: https://github.com/opencv/opencv/pull/28242
Ported to 5.x: https://github.com/opencv/opencv/pull/26408
