### ISSUE TITLE
IMDecode on image with missing data interpolate the missing part of the image with previously IMDecoded images

### ISSUE THREAD

**Issue by kevincua-umbocv** [opencv/opencv#26488]
### System Information (Updated for 4.11.0 release)

OpenCV version: 4.10.0, 4.11.0
Operating System / Platform: Ubuntu 22.04, 24.04 / Debian 11 
Python 3.10.12

Also on Go 1.23.3 with GoCV 0.39.0 (although this is not supported by this repo)

### Detailed description

Issue is only on OpenCV 4.10.0 and 4.11.0 and as far as I tested not in 4.9.0 and 4.8.1.
IMDecode on image that has missing parts will merge with previously IMDecoded images. This won't happen on the first IMDecode on the image with missing data, but will happen in the future ones. 

IMDecode on human
![human](https://github.com/user-attachments/assets/db9dbba8-8949-4b8b-a975-0b03725e5d07)

IMDecode on image with missing parts 
![corruptedimg](https://github.com/user-attachments/assets/4dc891dc-5cdc-4938-8125-72a5f5b48b7c)

IMWrite the IMDecoded image with missing parts (2nd loop)
![1output](https://github.com/user-attachments/assets/078849bb-1486-4d54-be70-334506f6e4be)

**SOLUTION**
Current solution to this is to downgrade opencv to 4.9.0

### Steps to reproduce

```
import cv2 

import numpy as np


print("OpenCV version:", cv2.__version__)

for i in range(10):
    with open('human.jpg', 'rb') as f:
        img_data = f.read()
    
    # Create a numpy array from the binary data
    buffer = np.frombuffer(img_data, dtype=np.uint8)
    
    image = cv2.imdecode(buffer, cv2.IMREAD_COLOR)
    
    with open('corruptedimg.jpg', 'rb') as f:
        img_data2 = f.read()
    
    # Create a numpy array from the binary data
    buffer2 = np.frombuffer(img_data2, dtype=np.uint8)
    
    # Decode the image
    image2 = cv2.imdecode(buffer2, cv2.IMREAD_COLOR)

    cv2.imwrite(f"{i}output.jpg",image2)

```
**ZIP FILE FOR IMAGE TO REPRODUCE**
[images.zip](https://github.com/user-attachments/files/17808904/images.zip)

### Issue submission checklist

- [X] I report the issue, it's not a question
- [X] I checked the problem with documentation, FAQ, open issues, forum.opencv.org, Stack Overflow, etc and have not found any solution
- [X] I updated to the latest OpenCV version and the issue is still there
- [X] There is reproducer code and related data files (videos, images, onnx, etc)

**Comment by kevincua-umbocv** [comment]
I included the zip file for the 2 images needed to reproduce the issue

**Comment by Linaname** [comment]
This issue is already fixed by this commit: https://github.com/opencv/opencv/pull/25864

Current behaviour: cv2.imdecode returns `None` if data is corrupted. This behaviour matches the documentation

**Comment by kevincua-umbocv** [comment]
I just tested this with 4.11.0. This is issue still persists. The image is decoded and because part of it is missing, it will take the other part from memory which is not good.

**Comment by kevincua-umbocv** [comment]
was still able to replicate with 4.12.0 on gocv

**Comment by jeremy-patterson1** [comment]
Re-verified this issue on the current 5.x branch using the in-repository Debug Python build ( OpenCV 5.1.0-dev ) and the original  human.jpg  / truncated  corruptedimg.jpg  files.
Results:
-  imdecode : the corrupted JPEG returned  None  on every iteration.
-  imread : repeated decodes produced identical output, with no content from the previously decoded image.
The current 5.x branch bundles libjpeg-turbo 3.1.2. The issue was caused by libjpeg-turbo 3.0.3, used by OpenCV 4.10 and 4.11, and was fixed upstream in libjpeg-turbo 3.1.0.
Version summary:
- OpenCV 4.9 / libjpeg-turbo 2.1.x: not affected
- OpenCV 4.10–4.11 / libjpeg-turbo 3.0.3: affected
- OpenCV 4.12+ and 5.x / libjpeg-turbo 3.1.x: not affected
This appears to be fixed by the libjpeg-turbo dependency upgrade. Recommend closing the issue.
