### ISSUE TITLE
Error while detecting and decoding QR code

### ISSUE THREAD

**Issue by daveisfera** [opencv/opencv#27807]
### System Information

The function to detect and decode QR codes runs into an error on the attached image

### Detailed description

Here's the error:
```
Traceback (most recent call last):
  File "/Users/dlj/projects/qr_test/detect_qr_bug.py", line 15, in <module>
    _detect_qr_bug(argv[1])
    ~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/dlj/projects/qr_test/detect_qr_bug.py", line 11, in _detect_qr_bug
    data, bbox, c = qr_detector.detectAndDecode(img)
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
cv2.error: OpenCV(4.12.0) /Users/runner/work/opencv-python/opencv-python/opencv/modules/objdetect/src/qrcode.cpp:2961: error: (-2:Unspecified error) in function 'virtual std::string cv::ImplContour::decode(InputArray, InputArray, OutputArray) const'
> Invalid QR code source points (expected: 'contourArea(src_points) > 0.0'), where
>     'contourArea(src_points)' is 0
> must be greater than
>     '0.0' is 0
```

### Steps to reproduce

Here's the simple script to reproduce this with the attached image:
```
from sys import argv

import cv2 as cv


def _detect_qr_bug(filename: str) -> None:
    img = cv.imread(filename)

    qr_detector = cv.QRCodeDetector()

    data, bbox, c = qr_detector.detectAndDecode(img)


if __name__ == "__main__":
    _detect_qr_bug(argv[1])
```

### Issue submission checklist

- [x] I report the issue, it's not a question
- [x] I checked the problem with documentation, FAQ, open issues, forum.opencv.org, Stack Overflow, etc and have not found any solution
- [x] I updated to the latest OpenCV version and the issue is still there
- [x] There is reproducer code and related data files (videos, images, onnx, etc)

**Comment by daveisfera** [comment]
I thought there would be a way to attach the image that reproduces the problem, but I don't see one.

Here's a link to it:
https://drive.google.com/file/d/1exk-3Cjj2tAt1UOzXk9T0gZrKo7NsNAT/view?usp=sharing

**Comment by asmorkalov** [comment]
Looks like detector outputs some garbage and sanity check throws exception.

**Comment by asmorkalov** [comment]
please try QRCodeDetectorAruco. It works better,

**Comment by jasseeeem** [comment]
@daveisfera You can close this issue now. The fix has been merged to 4.x.

**Comment by asmorkalov** [comment]
Current solution rejects invalid boxes in decoding stage, but does not fix the original issue in detector.
