### ISSUE TITLE
CUDA implementation of cv::inRange()

### ISSUE THREAD

**Issue by lopsided98** [opencv/opencv#6295]
It seems that the CUDA module could benefit from an implementation of the `inRange()` function. The `threshold()` function already exists for CUDA, but this only works on one channel images.

Since `threshold()` already exists, it seems that it should be possible/simple to implement `inRange()` as well, since it is a similar operation, but I may be wrong.

I would look into this myself, but I don't have experience with writing CUDA kernels.

**Comment by wykvictor** [comment]
I wrote a simple CUDA kernel to simulate inRange() in CPU for Mat with three channels, here is the code for your reference(almost 20X speedup in GTX1070):

``` c++
__global__ void inRange_kernel(const cv::cuda::PtrStepSz<uchar3> src, cv::cuda::PtrStepSzb dst,
                               int lbc0, int ubc0, int lbc1, int ubc1, int lbc2, int ubc2) {
  int x = blockIdx.x * blockDim.x + threadIdx.x;
  int y = blockIdx.y * blockDim.y + threadIdx.y;

  if (x >= src.cols || y >= src.rows) return;

  uchar3 v = src(y, x);
  if (v.x >= lbc0 && v.x <= ubc0 && v.y >= lbc1 && v.y <= ubc1 && v.z >= lbc2 && v.z <= ubc2)
    dst(y, x) = 255;
  else
    dst(y, x) = 0;
}

void inRange_gpu(cv::cuda::GpuMat &src, cv::Scalar &lowerb, cv::Scalar &upperb,
                 cv::cuda::GpuMat &dst) {
  const int m = 32;
  int numRows = src.rows, numCols = src.cols;
  if (numRows == 0 || numCols == 0) return;
  // Attention! Cols Vs. Rows are reversed
  const dim3 gridSize(ceil((float)numCols / m), ceil((float)numRows / m), 1);
  const dim3 blockSize(m, m, 1);

  inRange_kernel<<<gridSize, blockSize>>>(src, dst, lowerb[0], upperb[0], lowerb[1], upperb[1],
                                          lowerb[2], upperb[2]);
}
```

**Comment by sarthakahuja11** [comment]
@wykvictor Thanks a lot for this snippet! I was looking for something similiar for my project. 
I just wanted to ask , as I guess this code was executing on your 1070 , does PtrStepSz  with uchar3 or uchar4 run with NVCC compilier as I will be using it . Please let me know if we actually need to care about that or NVCC might give an error when I run the code? Please tell me whatever things need to be taken into consideration in NVCC compiliation as I started learning CUDA few months back.
It would be a great help. Thank you!

**Comment by wykvictor** [comment]
@sarthakahuja11 Sorry for the late response. How is your project going on? The type "PtrStepSz" is defined in OpenCV, so all you need is to include/link with OpenCV(should be complied with CUDA support). I think the version of NVCC compilier is not a problem, as the kernel does not has any code and feature which needs higher compiler

**Comment by sarthakahuja11** [comment]
@wykvictor No problems at all, you responded that was more than enough!
Thanks a lot for it!
My project is going fine, its related to Road Sign Detection and Classifiacation.
Ya, Exactly that seems to be an issue.
I have OpenCV 2.4.9 , Ubuntu 14.04 and CUDA Toolkit 7.5 and currently a friend's laptop having NVIDIA 960M having same softwares on which I run my code after writing it in mine. 
So, I guess the issue I will face it would be in the cmake file with the linking of it with OPENCV as I have'nt done much of it before. 
Could you send me your cmake file of your above code? It would be of great help if you could mail me at 'sarthakahuja11@gmail.com' .
I promise I would'nt pass it on anywhere. Still if not possible please send me a sample cmake file of this fulfilling all requirements as I still am short of resources as mentoioned above.
Or my current cmake file is this, let me know if any changes are required in this to make a code similiar to your snippet work with it:

CXX=g++

#CUDA_INSTALL_PATH=/usr/local/cuda

CFLAGS= -I. -I$(CUDA_HOME)/include -I/usr/local/include

LDFLAGS= -L$(CUDA_HOME)/lib64 -lcuda -lcudart -L/usr/local/lib -lopencv_core -lopencv_gpu -lopencv_highgui -lopencv_imgproc -lopencv_ml

#Uncomment the line below if you dont have CUDA enabled GPU
#EMU=-deviceemu

ifdef EMU
CUDAFLAGS+=-deviceemu
endif

all:
	$(CXX) -c main.cpp -o main.o $(CFLAGS) -m64
	nvcc $(CUDAFLAGS) -c kernel_gpu.cu -o kernel_gpu.o
	$(CXX) main.o kernel_gpu.o -o grayscale $(LDFLAGS) 

clean:
	rm -f *.o grayscale


Waiting eagerly for your reply!
Thanks a ton!

**Comment by wykvictor** [comment]
@sarthakahuja11 You can refer to "OpenCV and Cuda related lines" in the cmake file [linkA](https://github.com/wykvictor/AprilTag-GPU/blob/master/CMakeLists.txt#L15-L33) and [linkB](https://github.com/wykvictor/AprilTag-GPU/blob/master/src/CMakeLists.txt).
I haven't update that repo for months, but some code snippet in the CMakeLists could be a reference, and it's a CMake style file not like the Makefile you posted. Pls let me know if you have further questions.

**Comment by mikkab** [comment]
@wykvictor good sample. thank you

**Comment by amiller27** [comment]
Is anyone currently planning to actually implement this as part of OpenCV?  I'd be willing to give it a shot if no one else is.

**Comment by SamCarlberg** [comment]
@amiller27 Have you done anything on this? I'm willing to take a stab at it if you haven't already.

**Comment by amiller27** [comment]
@SamCarlberg No, I never did.  Have at it!

**Comment by hexenskull** [comment]
Hello @wykvictor ! First I would like to say thank you for your contribution is such a great project!
Unfortunately the new opencv 3.3 still doesn't have the inRange implementation for GPU so I was trying to use your snippet and seems it's not working for me...

I'm using Jetson TX1 board.
So I successfully compiled my C++ opencv project with the code you provide for cuda with @sarthakahuja11 Makefile
Now I'm struggling to make it work.
The problem is that on runtime it doesn't write any data in destination GpuMat.
Here I can provide you my code:

```
//---------------------inRange_gpu.cu-----start-----------
#include "inRange_gpu.h"

__global__ void inRange_kernel(const cv::cuda::PtrStepSz<uchar3> src, cv::cuda::PtrStepSzb dst,
                               int lbc0, int ubc0, int lbc1, int ubc1, int lbc2, int ubc2) {
  int x = blockIdx.x * blockDim.x + threadIdx.x;
  int y = blockIdx.y * blockDim.y + threadIdx.y;

  if (x >= src.cols || y >= src.rows) return;

  uchar3 v = src(y, x);
  if (v.x >= lbc0 && v.x <= ubc0 && v.y >= lbc1 && v.y <= ubc1 && v.z >= lbc2 && v.z <= ubc2)
    dst(y, x) = 255;
  else
    dst(y, x) = 0;
}

void inRange_gpu(cv::cuda::GpuMat &src, cv::Scalar &lowerb, cv::Scalar &upperb,
                 cv::cuda::GpuMat &dst) {
  const int m = 32;
  int numRows = src.rows, numCols = src.cols;
  if (numRows == 0 || numCols == 0) return;
  // Attention! Cols Vs. Rows are reversed
  const dim3 gridSize(ceil((float)numCols / m), ceil((float)numRows / m), 1);
  const dim3 blockSize(m, m, 1);

  inRange_kernel<<<gridSize, blockSize>>>(src, dst, lowerb[0], upperb[0], lowerb[1], upperb[1],
                                          lowerb[2], upperb[2]);
}

//---------------------inRange_gpu.cu-----end-----------

//---------------------inRange_gpu.h-----start-----------
#ifndef __TEST__
#define __TEST__

#ifndef SKIP_INCLUDES
#include <vector>
#include <memory>
#include <iosfwd>
#include <iostream>
#endif

#include "opencv2/highgui/highgui.hpp"
#include "opencv2/imgproc/imgproc.hpp"
#include "opencv2/core/core.hpp"
#include "opencv2/core/cuda.hpp"
#include "opencv2/videoio.hpp"
#include "opencv2/cudafilters.hpp"
#include "opencv2/cudaimgproc.hpp"
#include "opencv2/cudaarithm.hpp"


void inRange_gpu(cv::cuda::GpuMat &src, cv::Scalar &lowerb, cv::Scalar &upperb,
                 cv::cuda::GpuMat &dst);


#endif /* __TEST__ */
//---------------------inRange_gpu.h-----end-----------

//---------------------main.cpp-----start-----------
#include "opencv2/highgui/highgui.hpp"
#include "opencv2/imgproc/imgproc.hpp"
#include "opencv2/core/core.hpp"
#include "opencv2/core/cuda.hpp"
#include "opencv2/videoio.hpp"
#include "opencv2/cudafilters.hpp"
#include "opencv2/cudaimgproc.hpp"
#include "opencv2/cudaarithm.hpp"

cv::Mat frame(WIDTH, HEIGHT, CV_8UC3, cv::Scalar(0, 0, 0));
cv::Mat frameHsv(WIDTH, HEIGHT, CV_8UC3, cv::Scalar(0, 0, 0));


int main(int argc, char **argv)
{
       // Create a window
	 cv::namedWindow("hsv", 1);

	 //Create trackbar to change brightness
	int iHh = 255;
	cv::createTrackbar("Hh","hsv",&iHh,255);
	int iHl = 24;
	cv::createTrackbar("Hl","hsv",&iHl,255);
	int iSh = 255;
	cv::createTrackbar("Sh","hsv",&iSh,255);
	int iSl = 31;
	cv::createTrackbar("Sl","hsv",&iSl,255);
	int iVh = 255;
	cv::createTrackbar("Vh","hsv",&iVh,255);
	int iVl = 0;
	cv::createTrackbar("Vl","hsv",&iVl,255);

	//open camera number
	cv::VideoCapture cap;
	cap.open(0);
	
	// beginning of while loop that interrupts with ESC
	for(;;)
	{
		maskedDiff = cv::Mat::zeros(1, 1, CV_8UC3);
		cv::Scalar lowerFilter(iHl, iSl, iVl);
		cv::Scalar higherFilter(iHh, iSh, iVh);

		cv::cuda::GpuMat frameGPM;
		cv::cuda::GpuMat frameHsvGPM;

                cap.grab();
		cap.retrieve(frame);

                // trying gpu inrange
		if (!(frame.data == NULL))
		{
			frameGPM.upload(frame);
			inRange_gpu(frameGPM, lowerFilter, higherFilter, frameHsvGPM);
			frameHsvGPM.download(frameHsv);
		}

                // saving mats to images
		cv::imwrite("images/frame.jpg", frame);
		cv::imwrite("images/gpu.jpg", frameHsv);

		if( cv::waitKey(10) == 27 ) break; // press esc to turn off the program
	{
        return 0;
}
```


the problem is that the first iteration of `for(;;)` loop I don't have any data in 'images/gpu.jpg' and on the second iteration the program crashes and the error message says:

```
...
unspecified launch failure in function upload
...
```

appreciate your help!
thank you!

**Comment by wykvictor** [comment]
@hexenskull The [inRange() ](http://docs.opencv.org/trunk/d2/de8/group__core__array.html#ga48af0ab51e36436c5d04340e036ce981)in OpenCV is used to threshold the Src image and output the Dst binary image(**One channel**). So the var frameHsv and frameHsvGPM should be initialized first as follows:
`
cv::Mat frameHsv(WIDTH, HEIGHT, CV_8UC1);
frameHsvGPM.create(WIDTH, HEIGHT, CV_8UC1); 
`
You can first use the CPU version of inRange() in OpenCV and then try to make this gpu version work.

**Comment by hexenskull** [comment]
Thank you @wykvictor ! The problem was so basic indeed. I just needed to initialise the output GpuMat 👍

**Comment by fadiaburaid** [comment]
Another approach to solving this issue would be using gpu::threshold() on the HSV image then using gpu::bitwise_and() function twice on the three threshold channels to get a binary single channel. I faced the same problem and came across your post and I assume many will face the same problem since there is no implementation for gpu::inrange() function. Here is the code I have implemented.

`gpu::GpuMat imgpu;
gpu::GpuMat hsv;
gpu::GpuMat shsv[3];
gpu::GpuMat thresc[3];
gpu::GpuMat temp;
gpu::GpuMat thres;

//Transform image to HSV
gpu::cvtColor(imggpu, hsv, COLOR_BGR2HSV);

//Split HSV 3 channels
gpu::split(hsv, shsv);

//Threshold HSV channels
gpu::threshold(shsv[0], thresc[0], 45, 90, THRESH_BINARY);
gpu::threshold(shsv[1], thresc[1], 100, 225, THRESH_BINARY);
gpu::threshold(shsv[2], thresc[2], 20, 225, THRESH_BINARY);

//Bitwise AND the channels
gpu::bitwise_and(thresc[0], thresc[1],temp);
gpu::bitwise_and(temp, thresc[2], thres);`

**Comment by aryus96** [comment]
@fadiaburaid If I understand well your solution. It's more a thresholding than an Inrange function. Indeed, you select only value that are above a threshold, you're not selecting values that are between two intervals.

**Comment by aryus96** [comment]
Hey guys,

I also tried to implement the inRangegpu on my Ubuntu 16.04 with OpenCV 3.3 and CUDA 9.0.

When I'm running the makefile, I have this error :
```

g++ -c main.cpp -o main.o -I. -I/include -I/usr/local/include -m64
nvcc  -c inRange_gpu.cu -o inRange_gpu.o
g++ main.o inRange_gpu.o -o grayscale -L/lib64 -lcuda -lcudart -L/usr/local/lib -lopencv_core -lopencv_gpu -lopencv_highgui -lopencv_imgproc -lopencv_ml
/usr/bin/ld: warning: libcudart.so.9.0, needed by /usr/local/lib/libopencv_core.so, may conflict with libcudart.so.7.5
/usr/bin/ld: main.o: undefined reference to symbol '_ZN2cv7imwriteERKNS_6StringERKNS_11_InputArrayERKSt6vectorIiSaIiEE'
//usr/local/lib/libopencv_imgcodecs.so.3.3: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Makefile:15: recipe for target 'all' failed
make: *** [all] Error 1

```

**Comment by fadiaburaid** [comment]
@aryus96 Sorry for the late reply. Yes you are right I have corrected that in my program but forgot to update my comment here. Now I have corrected it and it is functioning exactly the same way as Inrange function.

**Comment by Jelvani** [comment]
I guess inrange still isn't implemented in opencv 4.1 for CUDA. @wykvictor how do I include your code to be compiled with the rest of opencv? any help appreciated.

**Comment by kooscode** [comment]
Just an update to this, as of today, the InRange function still does not exist for GPU in OpenCV

The above code only does a threshold, i.e. it only evaluates a minimum floor value and ignores the ceiling..

There are two reasons, one is that the threshold function does not use a ceiling, only a floor.. the "maxval" parameter is actually what binary threshold wil use to replace the current value when threshold is met..

For example: 
- a value of 23 with at a threshold of 50 and maxval of 100 will become 0
- a value of 57 with a threshold of 50 and maxval of 100 will become 100 
- a value of 200 with a threshold of 50 and maxal of 100 will become 100

Meaning that any input value that falls above the threshold will be replaced with the maxval..

So - In order to really implement an "InRange" function you need to zero out values that are below your floor AND above your ceiling and then make everything within that range = maxval

The way to do this is to do use two thresholds, one for floor and one for ceiling and then only keep the data that falls between the two.

Like this:

```
//low and high ranges
cv::Scalar hsv_low(20, 70, 120);
cv::Scalar hsv_high(50, 200, 255);

//read source from file
cv::Mat src_img = cv::imread("myfile");

//upload img to gpu
cv::cuda::GpuMat src_img_gpu(src_img);

//all the parts to keep low and high thresholds
cv::cuda::GpuMat mat_parts[3];
cv::cuda::GpuMat mat_parts_low[3];
cv::cuda::GpuMat mat_parts_high[3];

//split into 3 channels H, S and V
cv::cuda::split(src_img_gpu, mat_parts);

//Use the inverse binary of upper threshold with bitwise_and to remove above limit values from lower threshold.

//find range between high and low values of H
cv::cuda::threshold(mat_parts[0], mat_parts_low[0], hsv_low[0], MAX_UCHAR, cv::THRESH_BINARY);
cv::cuda::threshold(mat_parts[0], mat_parts_high[0],  hsv_high[0], MAX_UCHAR, cv::THRESH_BINARY_INV);
cv::cuda::bitwise_and(mat_parts_high[0], mat_parts_low[0], mat_parts[0]);

//find range between high and low values of S
cv::cuda::threshold(mat_parts[1], mat_parts_low[1], hsv_low[1], MAX_UCHAR, cv::THRESH_BINARY);
cv::cuda::threshold(mat_parts[1], mat_parts_high[1],  hsv_high[1], MAX_UCHAR, cv::THRESH_BINARY_INV);
cv::cuda::bitwise_and(mat_parts_high[1], mat_parts_low[1], mat_parts[1]);

//find range between high and low values of V
cv::cuda::threshold(mat_parts[2], mat_parts_low[2], hsv_low[2], MAX_UCHAR, cv::THRESH_BINARY);
cv::cuda::threshold(mat_parts[2], mat_parts_high[2],  hsv_high[2], MAX_UCHAR, cv::THRESH_BINARY_INV);
cv::cuda::bitwise_and(mat_parts_high[2], mat_parts_low[2], mat_parts[2]);

cv::cuda::GpuMat tmp1, final_result;

//bitwise AND all channels.
cv::cuda::bitwise_and(mat_parts[0], mat_parts[1], tmp1);
cv::cuda::bitwise_and(tmp1, mat_parts[2], final_result);

cv::Mat img_final(final_result);`

```

**Comment by serbanc94** [comment]
Any update on this?

**Comment by kooscode** [comment]
@serbanc94  - use the code above that i posted.. thats a GPU version of in-range

**Comment by pwnorbitals** [comment]
That sounds like an interesting feature. Have we had any progress recently ?
