### ISSUE TITLE
Issue using stitching module

### ISSUE THREAD

**Issue by skruzic** [opencv/opencv#6969]
##### System information (version)

- OpenCV => 3.1.0-dev (master branch of 22nd July 2016)
- Operating System / Platform => Windows 10 64 bit
- Compiler => Visual Studio 2013
##### Detailed description

I wanted to do some research of image stitching with `stitching` module.

I compiled OpenCV 3.1.0-dev, master branch of 22nd July 2016 for **Python 2**. Then I executed following code:

```
import cv2

stitcher = cv2.createStitcher(False)
foo = cv2.imread('K:/foo.JPG')
bar = cv2.imread('K:/bar.JPG')
result = stitcher.stitch((foo,bar))
```

which resulted with following error message:

`error: K:\opencv_install\opencv\modules\python\src2\cv2.cpp:163: error: (-215) The data should normally be NULL! in function NumpyAllocator::allocate`

I'd appreciate some help regarding this issue. There were some workarounds for other functions like BackgroundSubtractorMOG2, but not for stitcher, so please help.

**Comment by yhoyhoj** [comment]
Can confirm this issue with OpenCV .

System information (version)
    OpenCV => 3.1.0.r1166.g5d7ee48-1
    Operating System / Platform => Linux (Archlinux) 64 bit
    Compiler => GCC

I'm getting this error with a similar code :  
`OpenCV Error: Assertion failed (The data should normally be NULL!) in allocate, file /home/yho/.cache/pacaur/opencv-git/src/opencv/modules/python/src2/cv2.cpp, line 150
Traceback (most recent call last):
  File "script/cv_controller.py", line 121, in <module>
    main_loop(simu.time())
  File "script/cv_controller.py", line 95, in main_loop
    stitch_images(cam_buffer)
  File "script/cv_controller.py", line 65, in stitch_images
    stitched = stitcher.stitch(images)
cv2.error: /home/yho/.cache/pacaur/opencv-git/src/opencv/modules/python/src2/cv2.cpp:150: error: (-215) The data should normally be NULL! in function allocate`

Using `cv2.ocl.setUseOpenCL(False)` which was cited as a workaround in #6081 did not help.

**Comment by Asalle** [comment]
Confirm the issue

System information (version)
OpenCV => 3.1.0-dev (master by 17 August 2016)
Operating System / Platform => Linux (Ubuntu 14.04) 64 bit
Compiler => GCC 4.8.4
Python 2.7

I would like to investigate this bug, but I am not very proficient OpenCV developer, so help and guidance needed and appreciated. I will not assign this one to myself, because I am not sure if I can handle it.

**Comment by ManuelZ** [comment]
I'm suffering the same problem here.

OpenCV => 3.1.0 (git checkout)
Operating System / Platform => Linux (Ubuntu 14.04) 64 bit
Compiler => GCC 4.8.4
Python 2.7.6

**Comment by bergersn** [comment]
Can confirm, having the same problem
OpenCV => 3.1.0 (git checkout) and 3.1.0-dev (master on 2016-11-09)
Operating System / Platform => Windows 7 64 bit
Compiler: Visual Studio 2015 Update 3 (32 bit)
Python 3.5.2 31 bit with Numpy 1.11.1 (Anaconda3 4.2.0 32 bit Distribution)

`cv2.error: D:\_d\OpenCV\opencv\modules\python\src2\cv2.cpp:152: error: (-215) The data should normally be NULL! in function NumpyAllocator::allocate`

Tried compiling without OpenCL and/or switching off OpenCL with `cv2.ocl.setUseOpenCL(False)` as suggested in linked [issue](https://github.com/opencv/opencv/issues/6081).

Also tried using `cv2.UMat`:
`
udimages == [<cv2.UMat object at 0x066433C0>, ...]
TypeError: images is not a numpy array, neither a scalar
`
... so, no luck.

If needed I could create a Callstack/Minidump.

**Comment by bergersn** [comment]
I looked at the Code and the other issues which seem related to this... 

The problems seems to be that the input to `Stitcher::stitch` is a `std::vector<cv::Mat>`. Now `Stitcher` only accepts `UMat`, so in `Stitcher::estimateTransform` it does this:
```
images.getUMatVector(imgs_);
rois_ = rois;
```
This calls `getUMat` on each `cv::Mat`, which uses the provided allocator... which is `NumpyAllocator`... which doesn't like data not being NULL.

I am not very familiar with the internals of OpenCV, but the question for me is... why? Why does it need to be NULL (or "should normally be NULL") and how do other algorithms handle this? It seems to me for "normal" allocations, when numpy is not involved, `data` is the original data which is then put into the allocated `(U)Mat`, which totally makes sense to me... how else would you get the original data in the new "buffer".. there are obviously 1000 and 1 ways, but this seems to me to be a "copy-constructor"-like situation...

**Comment by bergersn** [comment]
Got it running for me, but I would really need someone who knows his way around OpenCV <-> NumPy to take a look
cv2.cpp: acount line 148 (currently)
```c++
UMatData* allocate(int dims0, const int* sizes, int type, void* data, size_t* step, int flags, UMatUsageFlags usageFlags) const
{
        PyEnsureGIL gil;

        int depth = CV_MAT_DEPTH(type);
        int cn = CV_MAT_CN(type);
        const int f = (int)(sizeof(size_t)/8);
        int typenum = depth == CV_8U ? NPY_UBYTE : depth == CV_8S ? NPY_BYTE :
        depth == CV_16U ? NPY_USHORT : depth == CV_16S ? NPY_SHORT :
        depth == CV_32S ? NPY_INT : depth == CV_32F ? NPY_FLOAT :
        depth == CV_64F ? NPY_DOUBLE : f*NPY_ULONGLONG + (f^1)*NPY_UINT;
        int i, dims = dims0;
        cv::AutoBuffer<npy_intp> _sizes(dims + 1);
        for( i = 0; i < dims; i++ )
            _sizes[i] = sizes[i];
        if( cn > 1 )
            _sizes[dims++] = cn;
		PyObject* o = NULL;
		
		if( data != 0 )
		{
			o = PyArray_SimpleNewFromData(dims, _sizes, typenum, data);
		}
		else
		{
			o = PyArray_SimpleNew(dims, _sizes, typenum);
		}

        if(!o)
            CV_Error_(Error::StsError, ("The numpy array of typenum=%d, ndims=%d can not be created", typenum, dims));
        return allocate(o, dims0, sizes, type, step);
}
```

I think this is probably wrong on many levels considering "data" is probably just floating around with potentially no one cleaning it up...

**Comment by BrookRoberts** [comment]
Did 7787 definitely fix this issue for people?  With a build of 3.2.0 I was still hitting

`
cv2.error: /home/opencv/modules/python/src2/cv2.cpp:152: error: (-215) The given data should normally be NULL there! in function allocate`

Commenting out this line seemed to 'fix' the problem (at least, it successfully stitched some images together, and doing that didn't work for me in the previous release.)   OTOH, from comments above, maybe this line shouldn't be here - indeed it seems like the stitcher module.  Below is my repro:

```
>>> import cv2
>>> print (cv2.__version__)
3.2.0-dev
>>> stitcher = cv2.createStitcher(False)
>>> foo = cv2.imread("09500008-2101.png")
>>> bar = cv2.imread("09500008-2102.png")
>>> result = stitcher.stitch((foo,bar))
OpenCV Error: Assertion failed (The given data should normally be NULL!) in allocate, file /home/opencv/modules/python/src2/cv2.cpp, line 152
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
cv2.error: /home/opencv/modules/python/src2/cv2.cpp:152: error: (-215) The given data should normally be NULL! in function allocate

```

**Comment by pritasam** [comment]
>>> import cv2
>>> print (cv2.__version__)
3.2.0
>>> stitcher = cv2.createStitcher(False)
>>> foo = cv2.imread("09500008-2101.png")
>>> bar = cv2.imread("09500008-2102.png")
>>> result = stitcher.stitch((foo,bar))
OpenCV Error: Assertion failed (The given data should normally be NULL!) in allocate, file /home/opencv/modules/python/src2/cv2.cpp, line 152
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
cv2.error: /home/opencv/modules/python/src2/cv2.cpp:152: error: (-215) The given data should normally be NULL! in function allocate

I am also getting same error any fix on this ?

**Comment by pritasam** [comment]
Any updates on this bug ?

I am having the same issue

OpenCV Error: Assertion failed (The given data should normally be NULL!) in allocate, file /home/opencv/modules/python/src2/cv2.cpp, line 152
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
cv2.error: /home/opencv/modules/python/src2/cv2.cpp:152: error: (-215) The given data should normally be NULL! in function allocate

**Comment by Lukse** [comment]
Opencv 3.2.0-dev (from github)
Python 2.7
Windows 7 x64

With suggested commented lines I get another error. 

```
OpenCV Error: Assertion failed (u->originalUMatData->data == data) in deallocate, file C:\opencv3.2\source\opencv\modules\core\src\ocl.cpp,
line 4601
Traceback (most recent call last):
  File "Z:\5. Development\projects\LP0523-python_opencv_stich\images\01_test.py", line 9, in <module>
    result = stitcher.stitch((p1, p2))
cv2.error: C:\opencv3.2\source\opencv\modules\core\src\ocl.cpp:4601: error: (-215) u->originalUMatData->data == data in function deallocate

OpenCV Error: Assertion failed (u->originalUMatData->data == data) in deallocate, file C:\opencv3.2\source\opencv\modules\core\src\ocl.cpp,
line 4601
terminate called after throwing an instance of 'cv::Exception'
  what():  C:\opencv3.2\source\opencv\modules\core\src\ocl.cpp:4601: error: (-215) u->originalUMatData->data == data in function deallocate


This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.

```

**Comment by hawkerpl** [comment]
Opencv 3.2.0
Python 3.5
Windows 10 x64

Issue still exists.

**Comment by rfn123** [comment]
OpenCV 3.1.0
Python 2.7
Ubuntu Xenial 16.04

Still getting the same error

**Comment by SocraticPhoenix** [comment]
OpenCV 3.2.0
Python 2.7.13
Windows 7 x64

Also still getting the error...

**Comment by trinitybest** [comment]
Same here. :(
OpenCV 3.2
Python 2.7
Windows 10 x64

**Comment by stevenvdr** [comment]
Same here
OpenCV 3.2.0
Python 3.6.0
Windows 10 x64

**Comment by DrakeDawn** [comment]
got the same issue
OpenCV 3.2.0
Python 2.7.12
Ubuntu 16.04

**Comment by masonbrothers** [comment]
I am getting the same issue.
OpenCV 3.2.0
Python 2.7.13
Windows 10 x64

**Comment by Childhoo** [comment]
might be the reason listed here: https://github.com/opencv/opencv/issues/5667
since stitcher also needs flann matcher to find match points between images..

**Comment by sunkaiiii** [comment]
I got the same issue.
OpenCV 3.3.0 rc
Python 3.6.1
Windows 10 x64

**Comment by kim-tom** [comment]
Windows 10 64bit
Anaconda 4.4.0
Python 3.5.3

I fixed the same problem by upgrading the latest OpenCV3.3.
I downloaded the "opencv_python‑3.3.0+contrib‑cp35‑cp35m‑win_amd64.whl" from here. "cp35" means python3.5.

http://www.lfd.uci.edu/~gohlke/pythonlibs/#opencv

**Comment by sygfk** [comment]
Still having this issue
Windows 10 Pro 64bit
Anaconda 4.3.23
Python 3.6.1.final.0

**Comment by mshabunin** [comment]
@sygfk , what is your OpenCV version? `cv2.getBuildInformation()` can help.

**Comment by alalek** [comment]
> OpenCV 3.2.0

Fix is available with OpenCV 3.3.0
