### ISSUE TITLE
Doesn't build with TBB

### ISSUE THREAD

**Issue by Prakash19921206** [opencv/opencv#8659]
##### System information (version)

- OpenCV => 3.2
- Operating System / Platform => Windows 7 64bit
- Compiler => Visual Studio 2015 community Edition

##### Detailed description

normally it builds fine, but when i select `WITH_TBB `in cmake gui, there is no error when i click config or generate. visual studio there is compilation errors. Detailed post is [here](http://answers.opencv.org/question/143742/opencv-32-build-failed/)

**Comment by alalek** [comment]
@Prakash19921206 Please check this patch: #8664

**Comment by LaurentBerger** [comment]
Hi @alalek , I have checked patch #8664 using VS 2015 opencv-3.2.0-dev ( commit 10787c6 ) with tbb2017_20170226oss . Problem is solved for my configuration (opencv_core_AVX and and opencv_core_AVX2).

**Comment by LaurentBerger** [comment]
Hi @alalek 
Using patch #8664 I can build opencv-3.2.0-dev (branch is even with opencv:master) using Vs2015 and tbb2017_20170226oss. Tbb path is now included in project opencv_core_avx and opencv_core_avx2.

**Comment by Prakash19921206** [comment]
Can this issue be reopened?
now it built with tbb but for python and Install project i had an error

> Error	LNK1112	module machine type 'x64' conflicts with target machine type 'X86'	opencv_python3	C:\OpenCv_3.2\Build\modules\python3\python35_d.lib(python35_d.dll)

i check opencv_python3 project settings, it was set to win32
where else do i need to check to change x64 to x86 

when i run INSTALL project, i get following error in visual studio (i don't remember seeing this error message while building without tbb)

> Error	MSB3073	The command "setlocal
> "C:\Program Files (x86)\CMake\bin\cmake.exe" -DBUILD_TYPE=Release -P cmake_install.cmake
> if %errorlevel% neq 0 goto :cmEnd
> :cmEnd
> endlocal & call :cmErrorLevel %errorlevel% & goto :cmDone
> :cmErrorLevel
> exit /b %1
> :cmDone
> if %errorlevel% neq 0 goto :VCEnd
> :VCEnd" exited with code 1.	INSTALL	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets

its pointing to below line in Microsoft.cppCommon.targets
` <Exec Command="%(PostBuildEvent.Command)$(_BuildSuffix)" Condition="'%(PostBuildEvent.Command)' != ''"/>`

**Comment by alalek** [comment]
> 'x64' conflicts with target machine type 'X86'

This is not related to original issue - you need to specify the proper version of Python library (and install the right Python version too).

Mention on lines like these (CMake [stdout](http://pullrequest.opencv.org/buildbot/builders/master-win64-vc14/builds/10086/steps/cmake/logs/stdio)):
> -- Update variable PYTHON3_EXECUTABLE from environment: C:/utils/soft/python35-x64/python.exe
-- Found PythonInterp: C:/utils/soft/python35-x64/python.exe (found suitable version "3.5.2", minimum required is "3.4") 
-- Update variable PYTHON3_LIBRARY from environment: C:/utils/soft/python35-x64/Libs/python35.lib
-- Update variable PYTHON3_INCLUDE_DIR from environment: C:/utils/soft/python35-x64/include
-- Found PythonLibs: C:/utils/soft/python35-x64/Libs/python35.lib (found suitable exact version "3.5.2") 


> opencv_python3 project settings, it was set to win32

Where this is set?
Switch Win32/Win64 should be done via CMake generator parameter, you should not use MSVS for this. Check CMake output:

[Win32](https://pastebin.com/nLCRuCLi):
>--    CMake generator:             Visual Studio 14 2015

[Win64](http://pullrequest.opencv.org/buildbot/builders/master-win64-vc14/builds/10086/steps/cmake/logs/stdio):
>--    CMake generator:             Visual Studio 14 2015 Win64

BTW, Cleanup build directory if you change CMake settings/options/dependencies(python paths)/etc.

"Install" target requires successful build of other targets, so it fails for reason.

**Comment by Prakash19921206** [comment]
i think the problem was with python(x64) i had to install 32bit python, for now i removed python and INSTALL project succeeded. i have included opencv in a project. for debug mode i see following problem when i run .exe file

> Entry Point Not Found

> The Procedure entry point LoadPackagedLibrary could not be loacted in the dunamic link library KERNEL32.dll

i saw same error for release mode as well, but when i place "`tbb2017_20161128oss`" version of dll i don't see that error
i tried using the same version for debug, but it didn't work

`tbb2017_20170226oss` is the version of TBB is used while building opencv
i found [this ](http://stackoverflow.com/questions/17444197/opencv-dll-error-cant-locate-procedure-loadpackagedlibrary-in-kernel32-dll)stackoverflow link 
did it worked well on your end?
do you know the solution for this problem?  if not i'll open a new issue

Thanks

**Comment by alalek** [comment]
From SO Answer:
> From MSDN documentation - LoadPackagedLibrary. Minimum supported client is Windows 8, not Windows 7, so is impossible use this function.

So this problem can't be fixed by OpenCV. You just have wrong version of some component that doesn't support Win7:
- Windows SDK from MSVS
- your Python build
- TBB build (if not built from sources)
- something else that uses `LoadPackagedLibrary`

Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org

**Comment by Prakash19921206** [comment]
Thanks for your reply.
i removed python in cmake, and used precompiled TBB (WITH_TBB)
just wondering if it worked on your end.

**Comment by SplashX11** [comment]
@alalek I still get the error with the current master branch when compiling under raspbian on the PI 3.
I fixed the compilation of tbb as suggested in #7890  and it gets build. But then I get the ` fatal error: tbb/tbb.h: No such file or directory` error message.
I am using gcc (Raspbian 4.9.2-10)

**Comment by LaurentBerger** [comment]
issue discuss here is about windows. read first message please
