### ISSUE TITLE
Bug in cv::Algorithm::save / load

### ISSUE THREAD

**Issue by ereator** [opencv/opencv#9125]
##### System information (version)
- OpenCV => 3.2
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2015

##### Detailed description

The problem was firstly noticed for the **CvRTrees** algorithm. 
The .yml files, that were saved with the **save()** function by OpenCV v.3.2.0 may be read with **Algorithm::load()**, but algorithm **CvRTrees** stills empty (the data are not really loaded): the first attempt to all its **predict()** method causes an exception.
The .yml files, that were saved with the **save()** function by OpenCV v.3.1.0 may be successfully loaded in OpenCV v.3.2.0.
After a short investigation, it is appeared that the files been saved by OpenCV v.3.2.0 and by OpenCV v.3.1.0 are different:

**File saved with OpenCV v.3.2.0:**
``` 
%YAML:1.0
---
opencv_ml_dtree:
   is_classifier: 1
   var_all: 4
   ...
```

**File saved with OpenCV v.3.1.0:**
``` 
%YAML:1.0
opencv_ml_dtree:
   format: 3
   is_classifier: 1
   var_all: 4
   ...
```

So, the difference is only in the string ```format: 3``` 
As the quick fix, it is possible to add this string ```format: 3```  into the .yml. file, saved by OpenCV 3.2.0 in order to be able to read it .

##### Steps to reproduce
1.  Train the **CvRTrees** algorithm on train data
2. Save it using `save("fileName.yml")` function
3. Reset it using `clear()` function
4. Load it back using `Algorithm::load<RTrees>("fileName.yml")` fucntion
5. Try to use it, using `predict()` function.

In OpenCV 3.1.0 it will work, in OpenCV 3.2.0 it will cause an exception.

**Comment by alalek** [comment]
#5412 #6662 #5015

**Comment by sovrasov** [comment]
`CvRTrees` comes from `ml_old.hpp`. Models from `ml_old.hpp` and `ml.hpp` shouldn't be compatible and it was fixed in 3.2. Use `RTrees` in both cases: to save and to load.

**Comment by ereator** [comment]
Hello @sovrasov 
I have tried using `RTress` instead of `CvRTees` and the bug is still present.
I would like to point out one more time that in OpenCV 3.1 the bug is absent. So I think it is a new one and was not committed before in #5412 #6662 and #5015

**Comment by danielenricocahall** [comment]
@alalek it looks like this issue has been resolved in 3.3 according to the comment here https://github.com/Project-10/DGM/issues/8. I could not replicate on 3.4:
```
    cv::Ptr<RTrees> model = RTrees::create();
    Mat samples(2, 2, CV_32FC1);
    samples.at<float>(0,0) = 0;
    samples.at<float>(0,1) = 0;
    samples.at<float>(1,0) = 1;
    samples.at<float>(1,1) = 1;
    Mat responses(2, 1, CV_32S);
    responses.at<float>(0) = 0;
    responses.at<float>(1) = 1;
    cv::Ptr<TrainData> trainData = TrainData::create(samples, cv::ml::ROW_SAMPLE, responses);
    model->train(trainData);
    string file = tempfile(".yml");
    model->save(file.c_str());
    model->clear();
    model = Algorithm::load<RTrees>(file);
    Mat test(1, 2, CV_32FC1);
    model -> predict(test);
```
I believe this can be closed.

**Comment by SangKyoungPark** [comment]
Finally, I can't read the Opencv 3.2 version.
So, Can you tell me about the RandomForest loading method?
Perhaps, I think I can use the 'cv::ml::RTrees' Model.
Is this the only method?
If you think different method, I would receiveed that.
Thank you for reading .
